#!/bin/bash
#
# yntest
#

[ -n "$MYDIR" ] || {
	declare MYDIR=
	MYDIR="$(dirname "$(which "$(basename "$0")")")"
}

[ -n "$MYLIB" ] || {
	declare MYLIB=
	MYLIB="$MYDIR"/lib
}

[ "$ui_loaded" ] || source "$MYLIB"/ui.source

declare usagestr=
usagestr=$(
cat <<EOF

$(basename "$0")\0
EOF
)

# control_c: run if user hits control-c
#
# Global
#   CTLC_EXIT - bash environment variable
#
control_c() {
	echo -e "\nCtrl-c detected\nCleaning up and exiting."
	exit $CTLC_EXIT
}

main() {
	local yup

	getyn "answer yes or no" yup
	$yup && echo "yes" || echo "nope"

	ui_exit ui_exit_ok
}

main "$@"
