#!/bin/bash
# ark2host
#
# Copy one archive to a remote host and unpack it.
#

usage=$(
cat <<EOF
$0 <user@host> [-f file]
	-f file	- send only the named archive

EOF
)

function do_usage {
	echo "$usage"
	exit 1
}

argc=$#
[ $argc -lt 1 ] && do_usage

remote=${!argc}

sshcmd="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
rsyncmd="rsync -vat --no-owner --no-group"
file=""
user=""

while getopts "cf:" OPTION; do
	case "$OPTION" in
		f )
			file="$OPTARG"
			[ "$file" ] || do_usage
			;;
		* )
			do_usage
			;;
	esac
done

user="$(echo "$remote" | cut -d'@' -f1)"
hos="$(echo $remote | cut -d'@' -f2)"

echo "connecting with $remote..."
$rsyncmd ~/ark/$file $remote:ark/$file
runremote $user $hos ~/bin/init-my-stuff $user
echo
exit
