#!/bin/bash
# ark2host
#
# Copy one archive to a remote host and unpack it.
#

usage=$(
cat <<EOF
$0 [-f file]
	-f file	- send only the named archive

EOF
)

function do_usage {
	echo "$usage"
	exit 1
}

argc=$#
[ $argc -lt 1 ] && do_usage

remote=${!argc}

file=""
user=""

while getopts "cf:" OPTION; do
	case "$OPTION" in
		f )
			file="$OPTARG"
			[ "$file" ] || do_usage
			;;
		* )
			do_usage
			;;
	esac
done

user="$(echo "$remote" | cut -d'@' -f1)"
hos="$(echo $remote | cut -d'@' -f2)"

echo "connecting with $remote..."
rsync -vat ~/ark/$file $remote:ark/$file
runremote ~/bin/init-my-stuff $user $hos $user
echo
exit
