#!/bin/bash
#
# arksync 0.1

usage=$(
cat <<EOF
$0 [OPTION]
	-c		- confirm before sending archive
	-f file		- send only the named archive
EOF
)

query=false
answer="y"
file=""
remote=""
user=""

rsyncmd="rsync -vat --no-owner --no-group"

while getopts "cf:" OPTION; do
	case "$OPTION" in
		c )
			query=true
			;;
		f )
			file="$OPTARG"
			;;
		* )
			echo "unrecognized option"
			echo "$usage"
			;;
	esac
done

echo

for remote in \
"root@dl380g8" \
"root@bl460cg7" \
"root@hp-octane-01" \
"camuso@dl380g8" \
"camuso@hp-octane-01" \
"camuso@desktop"
do
	user="$(echo $remote | cut -d'@' -f1)"
	hos="$(echo $remote | cut -d'@' -f2)"

	if $query; then
		echo -n "rsync ~/ark/$file with $remote (y/n)? "
		read -n1 answer
		echo
	fi

	[ "$answer" == "q" ] && exit 1

	if [ "$answer" == "y" ]; then
		echo "connecting with $remote..."
		$rsyncmd ~/ark/$file $remote:ark/$file
		runremote ~/bin/fixup-rsync $user $hos $user
		echo
	fi
done

