#!/bin/bash
#
# arksync 0.1

usage=$(
cat <<EOF
$0 [OPTION]
	-c		- confirm before sending archive
	-f file		- send only the named archive
EOF
)

query=false
answer="y"
file=""
remote=""
user=""

rsyncmd="rsync -vat --no-owner --no-group"

function do_exit {
	echo "$usage"
	exit 1
}

while getopts "cf:" OPTION; do
	case "$OPTION" in
		c )
			query=true
			;;
		f )
			file="$OPTARG"
			[ "$file" ] || do_exit
			;;
		* )
			do_exit
			;;
	esac
done

echo

for remote in \
"root@hp-octane-01" \
"camuso@hp-octane-01" \
"tcamuso@desktop" \
"root@desktop" \
"tcamuso@dinar" \
"root@dinar"
do
	user="$(echo $remote | cut -d'@' -f1)"
	hos="$(echo $remote | cut -d'@' -f2)"

	if $query; then
		echo -n "rsync ~/ark/$file with $remote (y/n)? "
		read -n1 answer
		echo
	fi

	[ "$answer" == "q" ] && exit 1

	if [ "$answer" == "y" ]; then
		echo "connecting with $remote..."
		$rsyncmd ~/ark/$file $remote:ark/$file
		runremote $user $hos ~/bin/init-my-stuff $user
		echo
	fi
done

