#!/bin/bash

# appname=`basename $0 | sed s,\.sh$,,`
appname="bits"

# dirname=`dirname $0`
dirname="/home/tcamuso/bits"

tmp="${dirname#?}"

#if [ "${dirname%$tmp}" != "/" ]; then
#	dirname=$PWD/$dirname
#fi

LD_LIBRARY_PATH=$dirname
export LD_LIBRARY_PATH
echo $LD_LIBRARY_PATH

$dirname/$appname "$@"
