#!/bin/bash
#
# blacklist
#

cmdline=blacklist

usagestr=$(
cat <<EOF

blacklist <driver>

Put the driver in the /etc/modprobe.d/blacklist.conf file.
If you cannot rmmod the driver, you will need to reboot.
\0
EOF
)

usage() {
	echo -e "$usagestr"
	exit
}

[ "$1" == "-h" ] && usage
[ $# -eq 1 ] || usage

driver=$1
set -x
echo "blacklist $driver" >> /etc/modprobe.d/blacklist.conf
mv /boot/initramfs-$(uname -r).img /boot/initramfs-$(uname -r)-$driver.img
dracut /boot/initramfs-$(uname -r).img $(uname -r)
set +x
