#!/bin/bash
#
# braceprofiler
#

cmdline=braceprofiler

usagestr=$(
cat <<EOF

braceprofiler <file>

Print every line in file that has either { or } in it.
Helps to determine if there is a missing brace.
\0
EOF
)

usage() {
	echo -e "$usagestr"
	exit
}

[ $# -eq 1 ] || usage

# read -r processes backslashes as ordinary characters rather than escapes.
#
while read -r line; do 
	[[ "$line" == *"{"* ]] && echo $line; 
	[[ "$line" == *"}"* ]] && echo $line; 
done < $1
