#!/bin/bash
#
# cputop

usagestr="
$(basename $0)

	Prints all the cpu info for the first core.
"

[ "$1" == "-h" ] && { echo "$usagestr"; exit 1; }

while read line
do
	trimmedline="$(echo $line | tr -d '[[:blank:]]')"
	# echo $trimmedline
	[ -z $trimmedline ] && break
	echo "$line"
done < /proc/cpuinfo

