#!/bin/bash
#
# cpuxspeed.sh
#

usagestr=$(
cat <<EOF

$(basename $0)

 Count the number of CPUs.
 Put CPU scaling in "ondemand" mode
 Put CPU scaling in "userspace" mode
 Set CPU speeds to min
 Set CPU speeds to max
 Put CPU scaling back into "ondemand" mode
\0
EOF
)

userstr="
Must be root to invoke $(basename $0)
"

[ $(id -u) -eq 0 ] || { echo "$userstr";  exit 1; }
[ "$1" == "-h" ] && { echo -e "$usagestr"; exit 1; }

cpu_count=$(ls -d /sys/devices/system/cpu/cpu*/cpufreq | wc -l)

max_cpu=$(( cpu_count - 1 ))

echo "Number of CPUs: $cpu_count"
AnyKey='Press any key to continue ...'

function pause {
	echo $1
	read -p "$AnyKey";
}

function dump_freq {
	case $1 in
		min )	arg='minumum'
				;;
		max )	arg='maximum'
				;;
		cur )	arg='current'
				;;
		* )             echo "Invalid parameter"
				usage
				;;
	esac
	pause "Here is a list of CPU $arg frequencies."
	echo -e " CPU: KHz\n ---- -------"
	for (( i = 0; i < cpu_count; i++ )); do
		khz=$(cat /sys/devices/system/cpu/cpu$i/cpufreq/cpuinfo_$1_freq)
		printf " %3d: $khz\n" $i
	done
	echo
}

function set_governor {
	echo "Setting all $cpu_count frequency scaling governors to \"$1\"."
	for (( i = 0; i < cpu_count; i++ )); do
		echo "$1" > /sys/devices/system/cpu/cpu$i/cpufreq/scaling_governor;
	done
	# cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
	echo
}

function set_speed {
	case $1 in
		min )	arg='minumum'
				;;
		max )	arg='maximum'
				;;
		* )             echo "Invalid parameter"
				usage
				;;
	esac
	echo "Setting your CPU speeds to their $arg values"
	for (( i = 0; i < cpu_count; i++ )); do
		cat /sys/devices/system/cpu/cpu$i/cpufreq/cpuinfo_$1_freq > \
		/sys/devices/system/cpu/cpu$i/cpufreq/scaling_setspeed;
	done
	dump_freq "cur"
}

# Set cpu frequency scaling governor to "ondemand".
#
echo "Here is a list of the current per-cpu scaling governors."
cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
echo

# Dump minimum frequencies and maximum frequencies.
#
dump_freq "min"
dump_freq "max"

# Set cpu frequency scaling governor to "userspace"
#
set_governor "userspace"
dump_freq "cur"

# Set CPUs to minimum frequency
#
set_speed "min"

# Set CPUs to maximum frequency
#
set_speed "max"

# Return control to "ondemand"
#
echo
set_governor "ondemand"
dump_freq "cur"

