#!/bin/bash

usage() {
	echo
	echo -e "\tdeleteline string file"
	echo
	echo -e "\tdelete the line containing the string in file."
	echo
	exit 0
}

[ $# -lt 2 ] && usage

string="$1"
file="$2"
# set -v
sed -i "/"$string"/d" "$file"
# set +v
