#!/bin/bash
#
# deletelinen

usagestr=$(
cat <<EOF

$(basename $0) n file

	Deletes the nth line of the file.
\0
EOF
)

usage() {
	echo -e "$usagestr"
	exit 0
}

[ "$1" == "-h" ] && usage
[ $# -eq 2 ] || usage

tfil="__temp__file__"

mode=$(stat --format '%a' $2)
touch $tfil
chmod $mode $tfil

awk -v line=$1 '{
        if (NR != line) {
                print $0;
        }
}' $2 > $tfil
mv $tfil $2
