#!/bin/bash

usage() {
	echo
	echo -e "\tdeleteline string file"
	echo
	echo -e "\tdelete the line containing the string in file."
	echo
	exit 0
}

[ "$1" == "-h" ] && usage
[ $# -eq 2 ] || usage

mode=$(stat --format '%a' $2)
string="$1"
file="$2"
# set -v
sed -i "/"$string"/d" "$file"
chmod $mode $file
# set +v
