#!/bin/bash
#
# delete-my-stuff

usagestr="
$(basename $0)

	Removes my environment and returns everything to the way it was
	before I installed my environment.

	However, it leaves a logfile of what was removed.
"

[ "$1" == "-h" ] && { echo -e "$usagestr"; exit 1; }

cd $HOME

logfile="$HOME/.deletemystuff.log"
touch "$logfile"
cat /dev/null > "$logfile"
echo >> "$logfile" 2>&1


for f in $(ls -rtd1 rcbak/{*,.*}); do
	name=$(basename $f);

	if [ -f $f ] && [ -f "$name.orig" ]; then
		mv -vf $name.orig $name 2>&1 | tee -a $logfile
	fi
done


for file in $(ls -1 ark/); do
	name=$(basename -s .tgz $file)
	rm -rvf $name 2>&1 | tee -a $logfile
done

exit 0
