#!/bin/bash

echo "# dmidecode | grep -e Date -e Vendor -e Version -e Product -e \"BIOS Revision\" | head -5"
dmidecode | grep -e Date -e Vendor -e Product -e Firmare -e Version -e "BIOS Revision" | head -5
