#!/bin/bash
#
treetop="/work/us/linux/"

cd $treetop

[ -d /sys/module/ipmi_si ] || modprobe -v ipmi_si

if [ $1 -eq 1 ]; then
	make drivers/watchdog/ipmi_wdt.ko


[ $1 -eq 1 ] && watchdog="drivers/watchdog/ipmi_wdt.ko" && mod="ipmi_wdt"
[ $1 -eq 2 ] && watchdog="drivers/char/ipmi/ipmi_watchdog.ko" && mod="ipmi_watchdog"

make $watchdog
[ -d /sys/module/$mod ] && rmmod -v $watchdog
insmod $watchdog #preaction=pre_nmi
# echo pre_nmi > /sys/module/ipmi_wdt/parameters/preaction

cd -

