#!/bin/bash

rev=""
show_b=true
declare -i optcount=0
declare -a alist		# alternate branch list
declare -a blist		# current branch list
declare notupstream="*LOCALBR*"

while getopts :p:rb OPTION; do
    case "$OPTION" in

	r ) rev="--reverse"
	    optcount=$((optcount+1))
	    ;;
	b ) show_b=false
	    optcount=$((optcount+1))
	    ;;
	p ) pathspec=$OPTARG
	    optcount=$((optcount+2))
	    ;;
	* ) echo "unrecognized option -$OPTION"
	    echo -e "$usagestr"
	    exit 127
    esac
done

shift $optcount
commit_expr="$1"
pathspec="$2"

blist=($(git log --oneline $rev --pretty=format:%h $commit_expr $pathspec))

for ((i=0; i < ${#blist[@]}; ++i)); do
	log=$(git log -1 ${blist[$i]} | tail -n +2)
	alist[$i]=$(echo "$log" | egrep -o "\b[0-9a-f]{40}\b")

	if [ $? -eq 0 ]; then
		printf -v astr " %s " $(gitnice -d -1 "${alist[$i]}")
	else
		tmp="$(gitnice -d -1 ${blist[$i]} | cut -d' ' -f2-)"
		tmp="${tmp:0:11}  ${tmp:12}"
		printf -v astr "%s%s" "$notupstream" "$tmp"
	fi

	if $show_b; then
		printf " %-9s %s\n" "${blist[$i]}" "$astr"
	else
		echo " $astr "
	fi
done

