#!/bin/bash
#
# findinclude
#

#
# Text attributes
#
attr_bold="\033[1m"
attr_under="\033[4m"
attr_OFF="\033[0m"

BLD="$attr_bold"
UND="$attr_under"
OFF="$attr_OFF"

declare -i optcount=0
declare -i _FOUNDIT_=32
declare -i _NOINCLUDES_=8
declare -i stat
declare incfile
declare srcfile
declare inclist

declare usagestr=$(
cat <<EOF

$(basename $0) [options] incfile srcfile

  Search the given source file for the given include file. If the include
  file we are seeking is not in the source file, then each of the include
  files in the source file will be recursively searched for the given
  include file.

  incfile - the include file we are seeking
  srcfile - the source file that we believe contains it or contains other
            include files that contain it.

  Options
  -h  - this help text
\0
EOF
)

usage() {
	echo -e "$usagestr"
	exit $1
}

while getopts h OPTION; do
    case "$OPTION" in

	h ) optcount=$((optcount+1))
	    ;;
	* ) echo "unrecognized option -$OPTION"
	    echo -e "$usagestr"
	    exit 127
    esac
done

shift $optcount
[ $# -eq 2 ] || usage 1

incfile="$1"
srcfile="$2"

IFS=
echo -e "\n$BLD\0findinclude $incfile $srcfile$OFF"
inclist=$(getallinclude $srcfile)
[ $? -eq $_NOINCLUDES_ ] && { echo -e "$BLD\tno includes$OFF"; exit 0; }
echo "$inclist"

#set -x
while read line; do
	echo "$line" | grep -w "$incfile"
	[ $? -eq 0 ] && { echo ""$srcfile" contains "$incfile""; exit $_FOUNDIT_; }
done <<< "$inclist"

while read line; do
	echo -e "$BLD\0parse $line for $incfile$OFF"
	[ -f "$line" ] || continue
	findinclude "$incfile" "$line"
	stat=$?
	[ $stat -eq $_FOUNDIT_ ] && exit 0
	# [ $stat -ne 0 ] && exit 1
done <<< "$inclist"
exit 1

