#!/bin/bash

remoteuser="$1"

if [ "$remoteuser" == "root" ]; then
	chown -v root.root /root
#	chmod -v g-w /root
else
	chown -v $remoteuser.$remoteuser /home/$remoteuser
#	chmod -v go-w /home/$1
fi

