#!/bin/bash
#
# g0

declare usagestr=$(
cat <<EOF

$(basename $0) 

Description:

Arguments:

\0
EOF
)

usage() {
	echo -en $usagestr
	exit 1
}

main() {
	gnome-terminal --geometry=100x48 &
}

main $@

exit 0
####################################################################################################
