#!/bin/bash

#
# Text attributes
#
declare BLD="\033[1m"
declare UND="\033[4m"
declare OFF="\033[0m"

default_index=$(grubby --default-index 2>/dev/null)

star=""
grubby --info=ALL 2>/dev/null | grep -A1 index | while read -r line; do
	if [[ "$line" =~ ^index=([0-9]+) ]]; then
		if [ "${BASH_REMATCH[1]}" -eq "$default_index" ]; then
			star=1
			echo -e "${BLD}* ${line}${OFF}"
		else
			star=""
			echo "  ${line}"
		fi
	elif [[ "$line" == "--" ]]; then
		echo "$line"
	else
		if [[ -n "$star" ]]; then
			echo -e "${BLD}* ${line}${OFF}"
			star=""
		else
			echo "  ${line}"
		fi
	fi
done
