#!/bin/bash

#
# Text attributes
#
declare BLD="\033[1m"
declare UND="\033[4m"
declare OFF="\033[0m"

declare grubconfigfile=$(find /boot -name grub.cfg)
declare grublist=$(grep "^menuentry" $grubconfigfile | cut -d "'" -f2)
declare olddef=$(grub2-editenv list | head -1 | cut -d'=' -f2)

index=0
while read line
do
    	let index++

	spacer="   "
	if [[ "$line" == "$olddef" ]]; then
		echo -en $BLD
		spacer=" * "
	fi

    	printf "%s%2d %s\n" "$spacer" $index "$line"
	echo -en $OFF

done <<< "$grublist"

