#!/bin/bash
#
# getallinclude
#

#
# Text attributes
#
attr_bold="\033[1m"
attr_under="\033[4m"
attr_OFF="\033[0m"

BLD="$attr_bold"
UND="$attr_under"
OFF="$attr_OFF"

declare -i optcount=0
declare filepath
declare inclist
declare incpath
declare dir


declare -i stat
declare -i _LOCALINCLUDE_=16
declare -i _NOINCLUDES_=8

declare usagestr=$(
cat <<EOF

$(basename $0) [options] filepath

  NOTE: This is intended to be executed from the top of a kernel tree.

  Parses the given files in a directory for #include declarations.

  filepath - the complete path, including directories to the file to search.

  Options
  -h  - this help text
\0
EOF
)

sage() {
	echo -e "$usagestr"
	exit $1
}

while getopts h OPTION; do
    case "$OPTION" in

	h ) optcount=$((optcount+1))
	    usage 1
	    ;;
	* ) echo "unrecognized option -$OPTION"
	    echo -e "$usagestr"
	    exit 127
    esac
done

shift $optcount
[ $# -eq 1 ] || { echo -e "\nNeed the filepath!"; exit 1; }

shopt -s extglob
shopt -s globstar

> .tmp.out

filepath="$1"
[ -f "$filepath" ] || {
	echo -e "\n\t$BLD$filepath not a file! $OFF"
	exit $_NOINCLUDES_
}

dir=$(dirname $filepath)
inclist="$(grep "#include" "$filepath" | cut -d':' -f2)"
[ "$inclist" ] || exit $_NOINCLUDES_

while read line; do
	incpath=$(getinclude "$line");

	# If the call to getinclude() returned the exit code _LOCALINCLUDE_
	# then the include path is local to the current directory.
	#
	[ $? -eq $_LOCALINCLUDE_ ] && echo $dir/$incpath || echo $incpath
done <<< "$inclist"
