#!/bin/bash
#
# getallinclude
#

declare -i optcount=0
declare filepath
declare inclist
declare incpath
declare dir


declare -i stat
declare -i _LOCALINCLUDE_=16

declare usagestr=$(
cat <<EOF

$(basename $0) [options] filepath

  NOTE: This is intended to be executed from the top of a kernel tree.

  Parses the given files in a directory for #include declarations.

  filepath - the complete path, including directories to the file to search.

  Options
  -h  - this help text
\0
EOF
)

getlist() {
	echo $1
	find $1 -type f -name \*.[ch] \
		-exec echo '{}' \; 
	#	-exec sh -c ' \
	#	grep "#include" $1 | cut -d':' -f2;' \
	#	sh {} \;
}

usage() {
	echo -e "$usagestr"
	exit $1
}

while getopts h OPTION; do
    case "$OPTION" in

	h ) optcount=$((optcount+1))
	    usage 1
	    ;;
	* ) echo "unrecognized option -$OPTION"
	    echo -e "$usagestr"
	    exit 127
    esac
done

shift $optcount
[ $# -eq 1 ] || { echo -e "\nNeed the filepath!"; usage 1; }

shopt -s extglob
shopt -s globstar


filepath="$1"
[ -f "$filepath" ] || {
	echo -e "\n"$filepath" not a valid file!"; usage 2;
}

dir=$(dirname $filepath)
inclist="$(grep "#include" "$filepath" | cut -d':' -f2)"

while read line; do
	incpath=$(getinclude "$line");

	# If the call to getinclude() returned the exit code _LOCALINCLUDE_
	# then the include path is local to the current directory.
	#
	[ $? -eq $_LOCALINCLUDE_ ] && echo $dir/$incpath || echo $incpath
done <<< "$inclist"
