#!/bin/bash
#
# getpatchwork
#

cmdtemp=getpatchwork

usagestr=$(
cat <<EOF

getpatchwork

Creates a set of patches from patchworks archive given the number of patches
and the full mbox link.

The user is queried for these items by invoking this script. If the script is
invoked with any parameters, the user will be given this usage text.

Patches are simply named x-y.patch, where x is the number of the patch and y is
the total number of patches.

RHEL patchworks is at http://patchwork.lab.bos.redhat.com/

\0
EOF
)

usage() {
	echo -e "$usagestr"
	exit
}

[ "$1" ] && usage

source ~/bin/lib/ui.source

# strindex string substring
#
# Return zero-based index of substring in string
# Returns -1 if substring is not found in string
#
function strindex {
	x="${1%%$2*}"
	[[ "$x" = "$1" ]] && echo -1 || echo ${#x}
}

getuser "Number of patches: " number
getuser "Full mbox link: " link
patchstr="/patch/"

lentopatch=$(($(strindex "$link" "$patchstr") + ${#patchstr} ))
linkhead=${link:0:$lentopatch}
linktail=${link:$lentopatch}
# echo "$linkhead --- $linktail"

patchnumlen=$(strindex "$linktail" "/")
patchnum=${linktail:0:$patchnumlen}
linktail=${linktail:$patchnumlen}
# echo "$patchnum --- $linktail"

for ((index=1; index <= number; index++)); do
	declare found=false
	declare newname=""
	declare temp=""

	link="$linkhead""$patchnum""$linktail"
	wget -q $link
	lastto=''
	lastfrom=''

	while IFS= read -r line; do
		if ! $found  \
			&& [ $(strindex "$line" "To:") -ge 0 ]; then
			lastto=$line
		fi
		if ! $found  \
			&& [ $(strindex "$line" "From:") -ge 0 ]; then
			lastfrom=$line
		fi
		if ! $found  \
			&& [ $(strindex "$line" "Subject: ") -ge 0 ] \
			&& [ $(strindex "$line" "RHEL") -ge 0 ]; then

			found=true

			# Remove the word "Subject: " from the temp
			#
			temp=$(echo "$line" | cut -d' ' -f2-)

			# Remove any brackets, parentheses, and quotes
			#
			temp=$(echo "$temp" | sed 's/[][{}<>(),"]//g')
			temp=$(echo "$temp" | sed "s/'//g")

			# Replace spaces, slashes, colons and semicolons
			# with hyphens
			#
			temp=$(echo "$temp" | sed "s\[/:; ]\-\g")

			# Create the new name
			#
			newname=$(printf "%s.patch" "$temp")

			echo "$newname"
			echo $lastto > "$newname"
			echo $lastfrom >> "$newname"
			echo $line >> "$newname"
			continue
		fi

		if $found \
		    && [ $(strindex "$line" "From patchwork") -ge 0 ]; then
		    # someone must have sent a reply
		    break
		fi

		$found && echo "$line" >> "$newname"

	done < index.html

	rm -f index.html
	let patchnum++
done

