#!/bin/bash
#
# gitampatch
#
# Patch the kernel from a mailbox and automate the process of applying,
# editing, and submitting the patches.
#
# Automate the patch process
#

VERSION="1.0"

#bind 'TAB:dynamic-complete-history'

# External source files
#
source ~/bin/lib/ui.source
source ~/bin/lib/project.source
source ~/bin/lib/gitutilities.source

b_ui_int_first_getyn=false

myshlvl=$SHLVL

# Herald
#
echo
echo "gitampatch $VERSION"
echo
echo -e "\tAutomates backporting patches from email."
echo -e "\tThe patches to be backported should be correctly formatted as"
echo -e "\temail for \"git am\" and they must have \".patch\" at the"
echo -e "\tend of their filenames.\n"
echo -e "\tPress 'x' to spawn a shell or 'q' to quitq at any prompt."
echo

###########################################
# Parameter Initialization
###########################################

declare index=0
declare boolindex=0
declare b_found_first_bool=false
declare gitbranch=$(get_gitbranch)
declare ui_bools=""
declare amcommitsfile=""
declare bpcommitsfile=""
declare b_use_bpcmtlog


# Init ui items
# -------------
# This loop enumerates and counts the items that will be stored in the
# project file. It also declares the boolean names whose values are stored
# in the project file and assigns values to them.
#
# Add new booleans to the end of the list.
# Add new non-boolean parameters to the top of the list.
#
for offset in \
prj_indir \
prj_outdir \
prj_bpcommits \
prj_b_create_patchset \
; do
	# The prj_set_item() function uses 1-based line numbers for indexing
	# into the project file. We inited the index variable to zero, so
	# lets start the loop by incrementing the index variable.
	#
	let index++

	# Assign the the value of the current loop counter (index) to the
	# prj file index variable referenced by the offset parameter defined
	# at the top of the for loop.
	#
	let $offset=$index

	if [ "${offset:3:3}" == "_b_" ]; then

		# The name of the boolean variable is the same as the project
		# file index variable, but with the leading "prj_" removed.
		#
		boolname="$(echo ${offset} | cut -d'_' -f2-)"
		declare $boolname

		# Create a string that contains all the names of the program's
		# booleans.
		#
		ui_bools=""$ui_bools" "$boolname" " # basically a strcat()

		[ "${!boolname}" == " " ] && eval $boolname=false
		let boolcount++
		if ! $b_found_first_bool; then
			boolindex=$index
			b_found_first_bool=true
		fi
	fi
done

# Initialize the prj_entries with the number of ui parameters counted in the
# above for-loop and init the project file.
#
prj_entries=$index
prj_init_prjfile ~/bin/.data/gitampatch.prj $index
prj_set_directory "source" $prj_indir indir
prj_set_directory "output" $prj_outdir outdir

# Create the project files
#
commitmessagefile=""$outdir"/commitmessage"
newcommitslog=""$outdir"/newcommits.log"
echo "newcommitslog: "$newcommitslog""

echo "Patches in "$indir""
ls "$indir"/*.patch
patchcount=$(ls "$indir"/*.patch | wc -l)
while [ $patchcount -eq 0 ]; do
	echo "There are no \"*.patch\" files in $indir."
	doyn "Want to spawn a shell to deal with it now?" "ui_sh_spawn"
	patchcount=$(ls "$indir"/*.patch | wc -l)
done

function chkconflicts {
	local conflicts=true

	while $conflicts; do
		git status
		getyn "Conflicts to fix?" conflicts
		if $conflicts; then
			ui_sh_spawn \
				"Be sure to commit your changes before exiting"
			git status
		else
			break
		fi
	done
}

b_newcmtloginited=false

getyn "Apply these patches now?" yn

if $yn; then

	# Apply the patches from the first branch.
	#
	for patch in $( ls "$indir"/*.patch ); do

		b_apply=false
		b_autocommit=false

		if ! $b_newcmtloginited ; then
			cat /dev/null > "$newcommitslog"
			# rm -f $newcommitslog
			b_newcmtloginited=true
		fi

		echo -e "Patch: "$attr_bold""$patch""$attr_OFF""
		doyn "Apply this patch?" "git am "$patch"" "" b_apply

		if $b_apply; then
			chkconflicts

			echo "$(git log -n1 --pretty=oneline | cut -d' ' -f1)" \
				>> "$newcommitslog"

			git log -n1
			getyn "Modify the commit message?" b_autocommit
		fi

		if $b_autocommit; then

			# Create the new commit message in a file consisting of ..
			#	empty line
			#	descriptor line, with leading whitespace trimmed
			#	three more empty lines
			#
			echo -e "\n" >> $commitmessagefile
			description=$(git log -n1 | head -5 | tail -1)
			#
			# Trim leading whitespace from description line
			#
			description=$(echo -e $description)
			echo "$description" >> $commitmessagefile
			echo -en "\n\n\n" >> $commitmessagefile
			#
			# Add the current commit message
			#
			git log -n1 >> $commitmessagefile
			echo -e "$attr_bold"
			echo -e "Edit the commit message ..."
			echo -e "$attr_OFF"
			git commit -s --amend --reset-author \
				      --file=$commitmessagefile --edit
		fi
	done
fi

# Create the patch set
#
getyn "Create a patch set?" ans

if $ans; then
	echo
	git_getsubjectprefix
	patchcount=$(cat "$newcommitslog" | wc -l)
	lastcommit=$(tail -1 $newcommitslog)
	echo
	git format-patch -s -$patchcount "$lastcommit" -o "$outdir"
fi

ui_sh_backout $myshlvl
echo
echo "Done."
echo
