#!/bin/bash
#
# gitbatcom
#

cmdline=gitbatcom

usagestr=$(
cat <<EOF

gitbatcom

Commit all files identified by git as "modified".

\0
EOF
)

usage() {
	echo -e "$usagestr"
	exit
}

[ $# -eq 0 ] || usage

declare gitstat="$(git status)"
declare modfound=false

for str in $gitstat; do
	[  "$str" == "modified:" ] && { modfound=true; continue; }
	if $modfound; then
		echo $str
		modfound=false
		git diff --cached $str
		read
		git commit $str
	fi
done
