#!/bin/bash
#
# gitbatcomst
#

cmdline=gitbatcom

usagestr=$(
cat <<EOF

$0

Commit all staged files identified by git as "modified".

\0
EOF
)

usage() {
	echo -e "$usagestr"
	exit
}

[ $# -eq 0 ] || usage

declare gitstat="$(git status)"
declare modfound=false

clear

for str in $gitstat; do
	[  "$str" == "modified:" ] && { modfound=true; continue; }
	if $modfound; then
		echo $str
		modfound=false
		git diff --cached $str
		read
		clear
		git commit $str
	fi
done
