#!/bin/bash
#
# gitforpat
#

declare -i argcount=2
declare -i optcount=0
declare cletter="--no-cover-letter"
declare reroll="--reroll-count=0"
declare startnumber=1

declare usagestr=$(
cat <<EOF

$(basename $0) [OPTIONS] directory commitspec -- pathspec

  Generate a patch set from a commit expression.

  directory  - directory that will contain the patch set
  commitspec - any commit expression, which can also be preceeded by other
               git-format-patch options.
  pathspec   - optional path from which to extrac the patches

  OPTIONS:
  -c      - generate a cover letter
  -v n    - version number of the patch
  -s n    - start patch series from number n

  The patch set will be created with the following git command.

  git format-patch \\\

	--no-renames \\\

	--numbered \\\

	--signoff \\\

	--stat=80 \\\

	--start-number=n \\\

	--output-directory <directory> \\\

	<commitspec> [-- pathspec]
\0
EOF
)

usage() {
	echo -e "$usagestr"
	exit $1
}

while getopts :cv:s: OPTION; do
    case "$OPTION" in

	c ) cletter="--cover-letter"
	    optcount=$((optcount+1))
	    ;;
	v ) reroll="--reroll-count=$OPTARG"
	    optcount=$((optcount+1))
	    ;;
	s ) startnumber=$OPTARG
	    optcount=$((optcount+1))
	    ;;
	* ) echo "unrecognized option -$OPTION"
	    echo -e "$usagestr"
	    exit 127
    esac
done

shift $optcount
[ $# -ge  "$argcount" ] || usage 1

directory="$1"
shift
commitspec=$@

echo -e "
git format-patch \\
	$cletter \\
	$reroll  \\
	--no-renames \\
	--numbered \\
	--signoff \\
	--stat=80 \\
	--start-number=$startnumber \\
	--output-directory $directory \\
	$commitspec
"

echo "Press any key to continue or ctrl-c to exit..."
read -n1

git format-patch \
	"$cletter" \
	"$reroll" \
	--no-renames \
	--numbered \
	--signoff \
	--stat=80 \
	--start-number=$startnumber \
	--output-directory "$directory" \
	$commitspec

