#!/bin/bash
#
# gitfirst - Find the git commit that first created a file
#
# Uses git log with --diff-filter=A to find the commit that added the file.
#
# This file uses shdoc-style annotations. See: https://github.com/reconquest/shdoc
#
# Common annotations:
#   @description  - Function/script description
#   @arg          - Function argument: @arg $1 type description
#   @set          - Global variable set: @set varname type description
#   @exitcode     - Exit code: @exitcode 0 description
#   @stdout       - Standard output description
#   @example      - Usage example
#
# Use 'docscript -f funcname <scriptname>' to view function documentation.
#
# Usage:
#   gitfirst drivers/usb/host/xhci.c
#   gitfirst include/linux/usb.h

declare usagestr=$(
cat <<EOF

$(basename $0) file

Description:
	Find the git commit that created the file.

Arguments:
	file - the file you want to find the first commit for
\0
EOF
)

# @description Display usage information and exit
#
# @exitcode 1 Always exits with error
usage() {
	echo -en "$usagestr"
	exit 1
}

# @description Find the commit that first added a file
#
# @arg $1 string Path to the file
#
# @stdout Git log output for the commit that added the file
#
# @exitcode 0 Success
# @exitcode non-zero File not found or git error
main() {
	[[ -z "$1" ]] && usage
	git log --diff-filter=A -- "$1"
	return $?
}

main "$@"
exit $?
