#!/bin/bash
#
# gitfor1pat
#


commit=$3
currentnumber="$2"
directory=$1

function usage() {
	echo
	echo "usage: gitfor1pat <directory> <patch-number> <commit>"
#	echo "usage: gitfor1pat <options> <directory> <patch-number> <commit>"
#	echo -e "\toptions      - any valid optons for \"git format-patch\""
	echo -e "\tdirectory    - destination of patch"
	echo -e "\tpatch-number - number of the patch"
	echo -e "\tcommit       - commit number of patch to be formatted"
	echo
	echo -e "\tPatch will be named \"patch-number.patch\""
	echo
	exit 1
}

[ "$1" == "?" ] && usage
[ $# -lt 3 ] && usage

echo "git format-patch -s --start-number "$currentnumber" "$commit" -o "$directory""
git format-patch -s --start-number "$currentnumber" "$commit" -o "$directory"
# mv "$directory"/"$currentnumber" "$directory"/"$currentnumber".patch

