#!/bin/bash
#
# gitrevcommits
#

cmdline=gitrevcommits

usagestr=$(
cat <<EOF

gitrevcommits commit tree

 Extracts all the oneline commits between two revisions for a given
 directory tree in reverse order and ouputs them to stdout.

 commit - commit string, e.g. \'commit1..commit2\' or \'commit..\'
 tree   - directory tree - for whole git tree, simply omit this arg

\0
EOF
)

usage() {
	echo -e "$usagestr"
	exit
}

[ $# -gt 1 ] || usage


commit="$1"
tree="$2"

if [ $tree ]; then
	git log "$commit" --oneline --no-merges --reverse -- "$tree"
else
	git log "$commit" --oneline --no-merges --reverse
fi

