#!/bin/bash

function git_getbranch {
	echo $(git branch | egrep \* | cut -d' ' -f2)
}

declare headdir="../headdir"
declare gitbranch="$(git_getbranch)"

git reset --hard $(cat "$headdir"/"$gitbranch")
