#!/bin/bash
#
# gitreview
#

cmdline=gitbatcom

usagestr=$(
cat <<EOF

$0

Review the diff of all files identified by git as "modified" using
git diff.

\0
EOF
)

usage() {
	echo -e "$usagestr"
	exit
}

[ $# -eq 0 ] || usage

declare gitstat="$(git status)"
declare modfound=false

clear

for str in $gitstat; do
	mod=false; ren=false; del=false; new=false;
	[  "$str" == "modified:" ] && mod=true
	[  "$str" == "renamed:" ]  && ren=true
	[  "$str" == "deleted:" ]  && del=true
	[  "$str" == "new file:" ] && new=true
	$mod || $ren || $del || $new && { modfound=true; continue; }
	if $modfound; then
		echo $str
		modfound=false
		git diff $str
		read -n1 -p "Press any key to continue or ctrl-c to quit ... "
		clear
	fi
done
