#!/bin/bash
#
# gitseekcommits
#

usagestr=$(
cat <<EOF

$0 [OPTION] commitsfile [path]

Where commitsfile is a list of commits with the commit in the first field
of each line (see ~/bin/gitprepcommits).

The optional path argument limits the search to git logs for that path.

Optional switches to modify the output.
  -a  - number of lines after (grep -A)
  -b  - number of lines before (grep -B)
  -c  - number of lines around center (grep -C)
  -h  - this help screen
\0
EOF
)

usage() {
	echo -e "$usagestr"
	exit $1
}

[ $# -gt 0 ] || usage

declare -i after=0
declare -i before=0
declare -i center=0
declare commitsfile=""
declare path=""
declare grepopts=""

while getopts ha:b:c: OPTION; do
    case "$OPTION" in

	h ) usage 1
	    ;;
	a ) after=$OPTARG
	    ;;
	b ) before=$OPTARG
	    ;;
	c ) center=$OPTARG
	    ;;
	* ) echo "unrecognized option -$OPTION"
	    usage 127
    esac
done

for opt in $@; do
	[[ "${opt:0:1}" == "-" ]] && shift
done

commitsfile=$1
path=$2

[[ $after > 0 ]]  && grepopts="$grepopts -A$after"
[[ $before > 0 ]] && grepopts="$grepopts -B$before"
[[ $center > 0 ]] && grepopts="$grepopts -C$center"

while read line; do
	[[ "${line:0:1}" == "#" ]] && continue
	commit=$(echo $line | cut -d' ' -f1)
	echo $commit
	git log $path | grep --color $grepopts $commit
	[[ $? == 0 ]] && echo
done < $commitsfile

exit 0
