#!/bin/bash
#
# gitup - update all the branches
#
# directory of top of git tree is passed as a parameter.
#

# Redirect stdout ( > ) into a named pipe ( >() ) running "tee"
#
exec > >(tee ../gitup.log)

# Without this, only stdout would be captured - i.e. your
# log file would not contain any error messages.
#
exec 2>&1

echo "cd "$1""
cd "$1"

echo "git remote update"
git remote update

echo "git clean -df"
git clean -df

while read line; do
	[ "${line:0:7}" != "[branch" ] && continue
	branch="$(echo "$line" | cut -d'"' -f2)"
	echo "================================================================="
	echo "git checkout -f "$branch""
	git checkout -f "$branch"
	echo "-----------------------------------------------------------------"
	echo "git pull"
	git pull
	echo
	git log -1 "$branch" | head -6
	branchcommit="$(git log -1 --oneline "$branch")"
	testbranch="$branch"".test"
	testcommit="$(git log -1 --oneline --ignore-missing "$testbranch")"
	git branch | grep "$testbranch"
	if [ $? -eq 0 ] && [ "$testcommit" != "$branchcommit" ]; then
		echo "-----------------------------------------------------------------"
		echo "Update the test branch."
		echo -e "\tgit branch -D "$testbranch""
		git branch -D "$testbranch"
		echo -e "\tgit checkout -b "$testbranch""
		git checkout -b "$testbranch"
		git log -1 "$branch" | head -6
	fi
	echo
done < .git/config

cd -
exit 0

