#!/bin/bash
#
# gl-upd-fork

declare usagestr=$(
cat <<EOF

$(basename $0) <fork> [branch]

Description:



Arguments:

\0
EOF
)

usage() {
	echo -en $usagestr
	exit 1
}

main() {
	fork="$1"
	branch="$2"

	git checkout main
	git fetch origin
	git rebase origin/main
	git push "$fork" main
	[ -n "$branch" ] && { git checkout "$branch"; git pull; }
}

main $@

exit 0

