#!/bin/bash
#
# gl-upd-fork

declare usagestr=$(
cat <<EOF

$(basename $0) <fork> [branch]

Description:
	[ -n "\$fork" ] || usage
	git checkout main
	git fetch origin
	git rebase origin/main
	git push "\$fork" main
	[ -n "\$branch" ] && { git checkout "\$branch"; git pull; }
\0
EOF
)

usage() {
	echo -e "$usagestr"
	exit 1
}

main() {
	fork="$1"
	branch="$2"

	[ -n "$fork" ] || usage
	git checkout main
	git fetch origin
	git rebase origin/main
	git push "$fork" main
	[ -n "$branch" ] && { git checkout "$branch"; git pull; }
}

main $@

exit 0

