#!/bin/bash
#

START1=$(date +%s)

files=$(find ./ -type f -name \*.i -exec sh -c \
	'grep -qm1 "ksymtab" $1; \
	[ $? -eq 0 ] || exit; \
	echo -n "$1 "' \
	sh '{}' \;)

END=$(date +%s)
DIFF=$(( $END - $START1 ))

minutes=$(( $DIFF / 60 ))
seconds=$(( $DIFF % 60 ))
echo
echo "That took $minutes minutes and $seconds seconds."
echo

START2=$(date +%s)

files=$(find ./ -type f -name \*.i -exec sh -c \
	'tac $1 | grep -qm1 "ksymtab" $1; \
	[ $? -eq 0 ] || exit; \
	echo -n "$1 "' \
	sh '{}' \;)

END=$(date +%s)
DIFF=$(( $END - $START1 ))

minutes=$(( $DIFF / 60 ))
seconds=$(( $DIFF % 60 ))
echo
echo "That took $minutes minutes and $seconds seconds."
echo
