#!/bin/bash
#
# hgrep 0.2
#

function usage {
	echo
	echo "hgrep [options] string dir/file | dir"
	echo -e "\tWhere filespec can include a regexp, like \"drivers/*.[hc]\""
	echo -e "\tOptions must come first and can be any valid grep options."
	echo -e "\tIf you omit the \"dir/file\" argument, the grep will be done for"
	echo -e "\tevery file in every directory from the PWD."
	echo
	echo -e "\tNOTE: You can have a directory without a file specification,"
	echo -e "\t      but you cannot have a file specification without a"
	echo -e "\t      directory."
	echo
	exit
}

argc=$#		# The number of arguments
pathspec="./*"	# Last space-separated token in the command line
filespec="*"	# Last '/' separated token in the command line
dirspec="./"	# '/' separated tokens excluding the filespec

declare -a optstr=""
declare -i index=0
declare -i n_opts=0
declare -i n_nonopts=0
declare -a grepstr
declare -i gpos

[ "$1" == "?" ] && usage

echo "Number of args: $argc"
for (( index = 1; index <= $argc; index++ )); do
	arg="${!index}"
	echo -n "arg_$index: "$arg""
	if [ "${arg:0:1}" == "-" ]; then
		optstr="$optstr $arg"
		echo " options: $optstr"
		let n_opts++
	else
		echo
	fi
done
echo "Number of opts: $n_opts, Options: $optstr"

n_nonopts=$(( $argc - $n_opts))
echo "Non-option args: $n_nonopts"

case $n_nonopts in
	1 ) 	grepstr="${!argc}"
		;;
	2 ) 	pathspec="${!argc}"
		gpos=$((argc - 1))
		grepstr="${!gpos}"
		;;
	* )	usage
		;;
esac
echo "pathspec: $pathspec, grepstr: $grepstr"

# If the entire path is a directory, then the filespec defaults
# to the "*" wildcard.
# Else, do pattern matching to extract the dirspec and filespec.
#
if [ -d "$pathspec" ]; then
	dirspec="$pathspec"
	filespec="*"
else
	dirspec="${pathspec%/*}/"
	filespec="${pathspec##*/}"
fi

echo "dirspec: $dirspec, filespec: $filespec"

# Need to get the grep version, because earlier versions do not support
# the '-T' option.
#
# The minimum version supporting the '-T' option is 2.6.0
#
mingrepversion=260

# Get the first line of the grep version and trim out everything but the
# version number.
#
grepversion=$(grep -V | head -1 | tr -cd '[[:digit:]]')

# If the grepversion is 2.6.0 or greater, then it supports '-T'
#
if [ $grepversion -ge $mingrepversion ]; then topt='T'; else topt=''; fi

execstr="find "$dirspec" -type f -iname "$filespec" \
	-exec grep -Hns"$topt" --color $optstr "$grepstr" '{}' \\;"
#echo $execstr

# $optstr cannot be in quotes, or grep will search for the null string
# and will assume that the $grepstr is the directory specification.
#
#find "$dirspec" -type f -iname "$filespec" \
#	-exec grep -Hns$te --color $optstr "$grepstr" '{}' \;
set -x
find "$dirspec" -type f -iname "$filespec" \
	-exec sh -c 'grep -q "$2" $3; if [ $? -eq 0 ]; then echo $3; \
	grep -ns --color $1 "$2" $3; fi' \
	sh "$optstr""$topt" "$grepstr" '{}' \;
set +x
