#!/bin/bash
#
# ifdefprofiler
#

cmdline=ifdefprofiler

usagestr=$(
cat <<EOF

ifdefprofiler <file>

Helps determine if there is a mismatched #if/#endif pair.
Prints every line that has #if, #ifdef, and #endif.
Lines are artificially indented to help with the matching.

\0
EOF
)

usage() {
	echo -e "$usagestr"
	exit
}

[ $# -eq 1 ] || usage

declare index=0
declare linenumber=0
declare file="$1"

indent() {
	local idx=$1
	for ((x=0; x < $idx; ++x)); do
		echo -n " "
	done
}

if ! [ -f "$1" ]; then
	echo "$1 is not a valid filename."
	echo
	exit 1
fi

IFS=	# prevent stripping of leading and trailing spaces
set -f	# disable pathname expansion

# read -r processes backspaces as ordinary characters, rather
#         rather than as escape sequences
#
while read -r line || [[ -n $line ]]; do
	let linenumber++
	if [[ $line == *"#if"* ]]; then
		printf "%5d: " $linenumber
		indent $index
		printf "%s\n" $line
		let index++
	fi

	if [[ $line == *"#endif"* ]]; then
		let index--
		printf "%5d: " $linenumber
		indent $index
		printf "%s\n\n" $line
		#[ $index -eq 0 ] && echo
	fi

done < "$file"
