#!/bin/bash
#
# insertline
#

cmdline=insertline

usagestr=$(
cat <<EOF

insertline <line-number> <inserted-text> <path/filename>
\0
EOF
)

usage() {
	echo -e "$usagestr"
	exit
}

[ $# -gt 2 ] || usage

file="$3"

awk -v line=$1 -v text=$2
	'NR==line {
		if ($0 == "\n"){
			print text;
		} else {
			print "\n";
			print text;
		}
	}1' $file > tmp

mv -f tmp $file

