#!/bin/bash
#
# insertfile
#

cmdline=insertfile

usagestr=$(
cat <<EOF

insertfile line-number dest-file source-file

Inserts source-file into dest-file starting the line after the given
line-number of the dest-file.

\0
EOF
)

usage() {
	echo -e "$usagestr"
	exit
}

[ $# -eq 3 ] || usage

linenum=$1
dest=$2
src=$3

sed -i ""$linenum"r $src" < $dest $dest
