#!/bin/bash

lc=$(cat $3 | wc -l)

if [ $1 -gt $lc ]; then
	echo "$2" >> $3
else
	awk -v line=$1 -v new_content="$2" '{
		if (NR == line) {
			print new_content;
		}
		print $0;
	}' $3 > temp
	mv temp "$3"
fi
