#!/bin/bash

declare usagestr=$(
cat <<EOF

$(basename $0)

Unloads and reloads the currently loaded ipmi modules.
\0
EOF
)

[ "$1" == "-h" ] && { echo -e "$usagestr"; exit 0; }

declare mod
declare ipmilist=$(lsmod | grep ipmi)

while read line; do
	mod=$(echo $line | cut -d' ' -f1)
	modprobe -rv $mod
done <<< "$ipmilist"

while read line; do
	mod=$(echo $line | cut -d' ' -f1)
	modprobe -v $mod
done <<< "$ipmilist"

