#!/bin/sh

__waitsecs() {
	local secs=$1
	local interval
	local reps

	[ $secs -le 0 ] && return 1

	case $((
		(secs <= 10)		   ? 1 :
		(secs > 10 && secs <= 100) ? 2 :
		(secs > 100)		   ? 3 : 0)) in
		(1) interval=.1; reps=$((secs * 10));;
		(2) interval=.5; reps=$((secs *  2));;
		(3) interval=1 ; reps=$secs;;
		(0) return 1;;
	esac

	echo -n "wait $1 seconds"
	for (( i=0; i<$reps; i++ )); do
		echo -n "."
		sleep $interval
	done
	echo
}

set -e

modprobe -v ipmi_poweroff
modprobe -v ipmi_watchdog
modprobe -v acpi_ipmi
# modprobe -v power_meter

for i in $(seq 0 10); do
	echo "Remove ipmi modules"
	# modprobe -rv power_meter
	modprobe -rv acpi_ipmi
	modprobe -rv ipmi_poweroff
	modprobe -rv ipmi_watchdog
	modprobe -rv ipmi_devintf
	modprobe -rv ipmi_si
	# modprobe -rv ipmi_ssif
	modprobe -rv ipmi_msghandler
	__waitsecs 2

	echo "Insert ipmi modules"
	modprobe -v ipmi_msghandler
	modprobe -v ipmi_si
	# modprobe -v ipmi_ssif
	modprobe -v ipmi_devintf
	modprobe -v ipmi_watchdog
	modprobe -v ipmi_poweroff
	# modprobe -v power_meter
	modprobe -v acpi_ipmi
	__waitsecs 2

done
echo "If you see this message, the test passed."
