#!/bin/bash

loopcount=1
while [ true ]
do
	echo
	echo "loopcount: $loopcount"
	echo "****************************************************"
	echo "ipmitool chassis selftest"
	echo "-------------------------"
	ipmitool chassis selftest
	echo
	echo "ipmitool chassis status"
	echo "-----------------------"
	ipmitool chassis status
	echo
	echo "ipmitool chassis bootdev"
	echo "------------------------"
	ipmitool chassis bootdev
	echo
	echo "ipmitool chassis bootparam"
	echo "--------------------------"
	ipmitool chassis bootparam
	echo
	echo "ipmitool chassis identify"
	echo "-------------------------"
	ipmitool chassis identify
	echo
	echo "ipmitool chassis policy list"
	echo "----------------------------"
	ipmitool chassis policy list
	echo
	echo "mc selftest"
	echo "-----------"
	ipmitool mc selftest
	echo
	echo "mc getenables"
	echo "-------------"
	ipmitool mc getenables
	echo
	echo "mc info"
	echo "-------"
	ipmitool mc info
	echo
	echo "mc guid"
	echo "-------"
	ipmitool mc guid
	echo
	echo "ipmitool mc getenables system_event_log"
	echo "---------------------------------------"
	ipmitool mc getenables system_event_log
	echo
	echo "ipmitool sdr"
	echo "------------"
	ipmitool sdr
	sleep 1
done
