#!/bin/bash
#
# ipv6off
#


declare usagestr=$(
cat <<EOF

$(basename $0)

Turns on ipv6 and enables it for subsequent boots.

\0
EOF
)

usage() {
	echo -e "$usagestr"
	exit $1
}

[ $# -eq 0 ] || usage 0

sysctl -w net.ipv6.conf.all.disable_ipv6=0
sysctl -w net.ipv6.conf.default.disable_ipv6=0
