#!/bin/bash

function usage {
	echo
	echo "kexecme kernel initrd"
	echo -e "\t\"kernel\" - kernel image file path"
	echo -e "\t\"initrd\" - initrd or initramfs filepath"
	echo
	exit 1
}

[ $# -ge 2 ] || usage

cmdline=$(cat /proc/cmdline)

echo $cmdline
set -x
kexec -l $1 --append='$cmdline' --initrd=$2
kexec -e
set +x
