#!/bin/bash
#
# kmodcopy
#

shopt -s extglob

declare kpath
declare libdir="/lib/modules/$(uname -r)/kernel"
declare arch=$(uname -i)

usagestr=$(
cat <<EOF

$(basename $0) kmod-directory

Where kmod-directory is the directory containing the kmods that will
be restored, relative to lib/modules/$(uname -r)/kernel/

Must be executed from the top of the kernel build tree.

The current kmods in the directory will be overwritten by the original
ones.
\0
EOF
)

nodir() {
        echo "$1 does not seem to exist."
        exit 1
}

[ $# -eq 1 ] || { echo -e "$usagestr"; exit 1; }
[ "$1" == "-h" ] && { echo -e "$usagestr"; exit 0; }

# Get the kmod path relative to the top of the kernel tree.
# If the last character is a slash, then remove it.
#
kpath="$1"
[ "${kpath: -1}" == "/" ] && kpath=${kpath:0: -1}

[ -d "$kpath" ] || nodir
[ -d "$libdir"/"$kpath" ] || nodir

cd "$libdir"/"$kpath"

# Restore the original .ko files, if they have not been saved already.
#
for f in $(ls -1 *.orig); do
	cp -v $f $(basename $f .orig).ko
done
