#!/bin/bash

# lsmod | while read a b; do echo $a:; modinfo $a | grep parm | sed -e 's/parm://'; done

# grepstr="$(alias grep)"
# unalias grep
echo
for kmod in $(lsmod | grep "$*" | cut -f1 -d' ')
do
	echo "$kmod:"
	echo "****************************************************************"
	# modinfo $kmod | grep parm | sed -e 's/parm: /\nparm: /'
	modinfo $kmod | grep parm
	echo
done
# foo=$(echo $grepstr | cut -c2- | rev | cut -c2- | rev)
# alias grep="$foo"
