#!/bin/bash
#
# commitcmp
#

[ "$MYDIR" ] || {
	declare MYDIR=
	MYDIR="$(dirname "$(which "$(basename "$0")")")"
}
[ "$MYLIB" ] || {
	declare MYLIB=
	MYLIB="$MYDIR"/lib
}
[ "$ui_loaded" ]            || source "$MYLIB"/ui.source
[ "$configmanager_loaded" ] || source "$MYLIB"/config-manager.source

declare -i background=
declare b_localus=false

# Other exit codes
declare -i exit_ok=0
declare -i exit_invarg=1
declare -i exit_invpath=2	# invalid path
declare -i exit_invdir=3
declare -i exit_disfil=4	# directory name is a file
declare -i exit_nodncmt=5
declare -i exit_nooutd=6	# directory name is empty

declare -a exitmsgary=

exitmsgary=(
""
"Invalid number of arguments."
" path does not exist."
" is an invalid directory name."
" is a file, not a directory."
" is not a valid downstream commit."
"You did not provide an output directory path:$MNU -od <outdir>$OFF"
)

exitme() {
	local -i exitval=$1
	local strarg=""
	local exitmsg

	if [ "$exitval" -ne $exit_ok ] && [ "$exitval" -ne $CTLC_EXIT ]; then
		[ $# -eq 2 ] && strarg=$2
		[ ${#exitmsgary[@]} -gt "$exitval" ] \
			&& exitmsg="${exitmsgary[$exitval]}"

		echo -e "$WRN$strarg$exitmsg$OFF"

		[ "$exitval" -ne 0 ] && echo -e \
			"${INF}Type $MNU$(basename "$0") -h$INF for help.$OFF"
	fi

	exit "$exitval"
}

# run if user hits control-c
#
control_c()
{
	echo -en "
	${WRN}Ctrl-c detected$INF
Cleaning up and exiting.$OFF
"
	exitme $CTLC_EXIT
}

declare -i optcount=0
declare uplog="upstream.log"
declare dnlog="downstream.log"
declare chlog="backport.log"
declare outdir=
declare updir=
declare upcmt=
declare dncmt=
declare searchstr=
declare path=

usage() {
	local usagestr

	usagestr=$(
cat <<EOF
$MNU
$(basename "$0") dncmt -od outdir [-ud updir] path [path-2 ... path-n]
$OFF
Uses scripts ${STA}gitnice$OFF and ${STA}extup$OFF to create a list of commits
to backport. Commits that have already been backported will have
a leading # to effectively comment them out to processing scripts, like
git-backport.

This must be run in the downstream (RHEL) repo directory.

Creates the following files in the <outdir>.
  $STA$uplog$OFF   - contains the upstream commits since <upcmt>
  $STA$dnlog$OFF - contains the downstream commits since <dncmt>
  $STA$chlog$OFF   - contains the upstream commits that have not yeat been
                   backported downstream.
$MNU
Arguments:$OFF
  Arguments and options can be entered in any order.
  Arguments without a leading hyphenated option tag are:
  $MNU
  dncmt$OFF - This would be the last downstream (RHEL) commit that was
          backported from upstream. The upstream commit will be extracted
	  from this downstream commit and used as a starting point to
	  search for new upstream commits for the given path(s).
  $MNU
  path$OFF - A space separated list of paths and files to be searched
         for new upstream commits for the backport.
$MNU
Options:$OFF$MNU
  -h$OFF         - this help text$MNU
  -ud ${OFF}updir  - directory with the upstream repo, default is ./$MNU
  -od ${OFF}outdir - REQUIRED Directory to contain ouput files.
$MNU
Example:$INF
  $(basename "$0") \\\

        d7f2756787f5 \\\

        -ud /work/upstream/kernel \\\

        -od ../backport/9.4/ipmi/ \\\

        drivers/char/ipmi include/linux/ipmi.h include/linux/ipmi_smi.h
$OFF
	Extract the upstream commit from RHEL commit d7f2756787f5 and
	search the upstream repo in /work/upstream/kernel for newer
	commits to the given paths.
$OFF
\0
EOF
)
	echo -en "$usagestr"
	exitme 0
}

get_pathopt() {
	local path=$1
	local -n optname="$2"

	[ -e "$path" ] || exitme $exit_invpath "$path"
	optname=$(realpath "$path")
}

get_varopt() {
	local var="$1"
	local -n varname="$2"

	varname="${var//,/ }"
}

test_help() {
	local opt="$1"

	shopt -s nocasematch
	[[ $opt =~ (h|help) ]] && { usage; exitme $exit_ok; }
	shopt -u nocasematch
}

# is_validcmtexpr
#
# Break the commit expression into separate strings, dividing on a
# double dot elipsis, and cycle through the resulting array to
# check each of the commits.
#
is_validcmtexpr() {
	local tmp=$1
	local -a cary=()
	local c

	cary=(${tmp//../ })

	for c in ${cary[@]}; do
		git rev-parse $c > /dev/null 2>&1 || return 1
	done

	return 0
}

# parseops() - parse the input options
#
# Needed multicharacter optionis, but didn't want to use longopts.
#
# Inputs: $@, the whole command line
#
# Globals:
# 	optcount
# 	upcmt
# 	dncmt
# 	usagestr
# 	searchstr
# 	path
#
parseops() {
	local arg=
	local opt=

	while (($# > 0)); do
	    arg="$1"

	    if [ "${arg:0:1}" == '-' ]; then
		opt="${arg:1}"

		shift
		case "$opt" in
		    ud ) get_pathopt "$1" updir
			 shift
			 continue
			 ;;
		    od ) get_pathopt "$1" outdir
			 shift
			 continue
			 ;;
		    S  ) get_varopt "$1" searchstr
			 ;;
		    *  ) echo "unrecognized option $arg"
			 echo -e "$usagestr"
			 exit 127
		esac

	    elif [ -e "$arg" ]; then
			path="$path $arg"
	    elif is_validcmtexpr "$arg"; then
			dncmt="$arg"
	    fi

	    shift
	done
}

# compare_strings() - compare strings
#    Compare the commits from the upstream and downstream commit logs
#    to identify those that have already been backported.
#    Output all commit lines to the log file, marking the ones that
#    were already backported with a leading #
#
# GLOBALS
#	chlog - output commits file
#	uplog - upstream commits file
#	dnlog - downstream commits file
#	outdir - directory for all the commit log files
#	upcmt - start from this upstream commit
#
compare_strings() {
	local uppath="$outdir/$uplog"
	local dnpath="$outdir/$dnlog"
	local chpath="$outdir/$chlog"
	local savedifs="$IFS"
	local upstr=
	local rhstr=
	local up	# one line from the upstream log
	local tmp
	local b_match=false
	local j		# upstr index
	local k		# rhstr index
	local rhcmt=

	# Instead of reading from the file, which limmits our debug
	# capabilites, create an array out of the lines in the file.
	# Set IFS to newline and then restore it after creating the
	# string arrays.
	#
	IFS=$'\n'
	upstr=($(< "$uppath"))
	rhstr=($(< "$dnpath"))
	IFS="$savedifs"

	# Zero the backport log file.
	:> "$chpath"

	for ((j = 0; j < ${#upstr[@]}; ++j)); do
		up=${upstr[j]}
		upcmt="${up:0:9}"

		for ((k = 0; k < ${#rhstr[@]}; ++k)); do
			tmp=$(echo "${rhstr[k]}" | cut -d' ' -f2)
			rhcmt="${tmp:0:9}"

			[[ "$rhcmt" == "$upcmt" ]] && {
				b_match=true
				break
			}
		done

		$b_match && echo "# $up" >> "$chpath" || echo "$up" >> "$chpath"
		$b_match && echo "# $up" || echo "$up"
		b_match=false
	done
}

init_env() {
	local bgtemp

	ui_setbg bgtemp

	MYDATA=$(realpath ./.data)
	[ -d "$MYDATA" ] || mkdir -p "$MYDATA"

	configfile="$MYDATA/mkbackportlog.conf"
	cfgtemplate="$MYLIB/mkbackportlog.conf"
	[ -f "$configfile" ] || cp "$cfgtemplate" "$configfile"

	cfg_start "$cfgtemplate" "$configfile"
	background="$bgtemp"
	cfg_set_item "background" "$background"
}

check_log() {
	log="$1"

	echo -e "${INF}Create : $STA$log$OFF"

	[ -f "$log" ] && {
		echo -en "$WRN$log exists.$OFF "
		echo -e "${INF}It will be overwritten if you continue.$OFF"
	}
}

get_mainbranch() {
	local line=
	local pline=
	local ary=()

	while read -r line; do
		if [[ $line == *"remote = origin"* ]]; then
			break
		else
			pline="$line"
		fi
	done < .git/config

	ui_strtok "$pline" '"' ary
	echo "${ary[1]}"
}

seek_str() {
	local prepend=
	local outfile=
	local commit
	local str

	[ -d "$updir" ] && { cd "$updir" || exitme $exit_invdir; }

	for str in $searchstr; do
		prepend=$(echo "$str" | cut -d' ' -f1)
		outfile="$outdir/$prepend-$chlog"

		echo -e "\n${STA}Creating $outfile$INF"
		: > "$outfile"
		while read -r line; do
			[ "${line:0:1}" == "#" ] && continue
			commit=$(echo "$line" | cut -d' ' -f1)
			git show "$commit" | grep -q -m1 "$str" || continue
			echo "$line" | tee -a "$outfile"
		done < "$outdir/$chlog"
	done
	cd - > /dev/null 2>&1 || exitme $exit_invdir
}

select_remote() {
	local -n gusr_cur="$1"
	local brstr=
	local brancharray=()

	# Get all the branches into one string
	brstr=$(git branch -r)

	# Filter out lines with '-> in them, because they are not branches
	while read -r s; do [[ $s == *"->"* ]] || brancharray+=("$s"); done <<< "$brstr"

	if [ ${#brancharray[@]} -gt 1 ]; then
		select_from_array brancharray "Remote Branches" gusr_cur
	else
		gusr_cur=${brancharray[0]}
		echo -e "$INF Only one branch in this repo: $STA$cur$OFF"
		echo -e "$INF Nothing else to choose from.$OFF"
	fi

	return 0
}

main() {
	local mainbranch
	local -a tmpary=()
	local localus

	init_env

        # Trap for control-c
        trap control_c SIGINT

	[ -f .git/config ] || {
		echo -e "${WRN}Not a repo directory!"
		echo -e "${INF}You must be in a repo directory."
		exit 1
	}
	mainbranch=$(get_mainbranch)

	test_help "$1"

	parseops "$@"

	# If no dncmt, then complain and exit.
	[ -n "$dncmt" ] || exitme $exit_nodncmt "$dncmt"

	# Exit if no outdir
	[ -n "$outdir" ] || exitme $exit_nooutd

	# If no updir, then use the current dir as default and prompt user to
	# select from available remotes for the upstream remote/branch.
	if [ -z "$updir" ]; then
		b_localus=true
		updir="./"
		select_remote localus
	else
		b_localus=false
	fi

	# Extract the upstream commit from the submitted RHEL commit, which is
	# the most recent RHEL commit under consideration, entered with the
	# -dc option.
	tmpary=($(extup -1 -r -n -u "$updir" "$dncmt"))
	upcmt="${tmpary[1]}"

	echo

	check_log "$outdir/$uplog"
	check_log "$outdir/$dnlog"
	check_log "$outdir/$chlog"

	$b_localus && echo -e "${INF}Upstream repo     : $STA$localus$OFF" \
		   || echo -e "${INF}Upstream repo     : $STA$updir$OFF"
	echo -e "${INF}Upstream commit   : $STA$upcmt$OFF"
	echo -e "${INF}Downstream branch : $STA$mainbranch$INF"

	if [ -n "$path" ]; then
		# If there's more than one path, show them all.
		if (($(wc -w <<< "$path") > 1)); then
			echo -e "${INF}Paths:$OFF"
			# shellcheck complains about vars without quotes, but
			# sometimes, it's what you really want.
			printf "  %s\n" $path
		else
			echo -e "${INF}Path:$OFF $path"
		fi
	fi

	echo
	echo -n "Press any key to proceed or CTRL-C to exit..."
	read -r -n1

	echo -e "$STA"
	[ -d "$updir" ] && { cd "$updir" || exitme $exit_invdir; }
	pwd
	echo -e "${STA}Creating $outdir/$uplog$INF"

	# If the upstream is local, checkout now.
	if $b_localus; then
		git checkout $localus > /dev/null 2>&1 & mypid=$!
		ui_waitonproc_tty $mypid .05 "Checking out upstream $localus"
	else
		gitnice -r -c -d --no-merges "$upcmt..HEAD" $path 2>&1 | tee "$outdir/$uplog"
	fi

	# Get the list of upstream commits starting from the one extracted from
	# the submitted RHEL commit with the -dc option.
	gitnice -r -c -d --no-merges "$upcmt..HEAD" $path 2>&1 | tee "$outdir/$uplog"

	# If we've checked out local upstream, switch back now.
	if $b_localus; then
		git switch - > /dev/null 2>&1 & mypid=$!
		ui_waitonproc_tty $mypid .05 "Returning to RHEL branch"
	fi

	echo

	echo -e "$STA"
	cd - || exitme $exit_invdir
	echo -e "${STA}Creating $outdir/$dnlog$INF"
	extup -r -n -u "$updir" "$dncmt..HEAD" $path 2>&1 | tee "$outdir/$dnlog"

	echo
	echo -e "${STA}Creating $outdir/$chlog$INF"
	compare_strings

	[ -n "$searchstr" ] && seek_str
	echo -e "$OFF"

	exitme $exit_ok
}

main "$@"

exitme $exit_ok

