#!/bin/bash
#
# mkbackportlog - Create a log of upstream commits to backport
#
# Searches upstream git history for commits touching specified paths
# and creates a backport log file for use with gort. Identifies commits
# already present in the downstream repository.
#
# Usage:
#   mkbackportlog              # Interactive mode
#   mkbackportlog -h           # Show help
#

[ "$MYDIR" ] || {
	declare MYDIR=
	MYDIR="$(dirname "$(readlink -f "$0")")"
}
[ "$MYLIB" ] || {
	declare MYLIB=
	MYLIB="$MYDIR"/lib
}
[ "$MYMAN"  ] || MYMAN="$MYDIR"/man
[ "$MYDATA" ] || MYDATA="$PWD"/.data

[ "$ui_loaded" ]            || source "$MYLIB"/ui.source
[ "$configmanager_loaded" ] || source "$MYLIB"/cfgmgr.source
[ "$ptversion_loaded" ]     || source "$MYLIB"/patchtools-version.source

# Exit Codes
declare -i exit_ok=0
declare -i exit_invarg=1
declare -i exit_invpath=2	# invalid path
declare -i exit_invdir=3
declare -i exit_disfil=4	# directory name is a file
declare -i exit_invhash=5	# not a hex number
declare -i exit_invcmt=6	# not a valid commit
declare -i exit_nooutd=7	# directory name is empty
declare -i exit_norepo=8	# not a repo directory
declare -i exit_noupcmt=9	# can't find upcmt in dncmt log
declare -i exit_nodncmt=10	# user did not supply a dncmt
declare -i exit_nopath=11	# user did not supply a path to search
declare -i exit_norepobr=12	# user did not supply an upstream repo/branch
declare -i exit_noupstream=13	# PWD does not have an upstream repo
declare -i exit_noupdir=14	# No upstream directory specified

declare -a exitmsgary=

# Exit messages
exitmsgary=(
""
"Invalid number of arguments."
" path does not exist."
" is an invalid directory name."
" is a file, not a directory."
" is not a valid commit hash."
" commit cannot be found in the logs"
"You did not provide an output directory path"
" is not a repo directory"
" commit log does not have a valid upstream commmit"
"You did not provide a downstream (RHEL) commit."
"You did not provide any paths to search, e.g. drivers/perf"
"You did not provide an upstream repo/branch to search"
" does not have an upstream repo."
"You did not specify an upstream repo directory"
)

# @description Exit with exit code and message
# @arg $1 int Exit code
# @arg $2 string Optional string argument for message
# @set exitmsgary array Exit message array (read)
# @exitcode * Returns the provided exit code
exitme() {
	local -i exitval=$1
	local strarg=""
	local exitmsg

	((exitval == exit_ok)) && exit $exitval

	if [ "$exitval" -ne $exit_ok ] && [ "$exitval" -ne $CTLC_EXIT ]; then
		[ $# -eq 2 ] && strarg=$2
		[ ${#exitmsgary[@]} -gt "$exitval" ] \
			&& exitmsg="${exitmsgary[$exitval]}"

		echo -e "$MNU$strarg$WRN$exitmsg$OFF"

		[ "$exitval" -ne 0 ] && echo -e \
			"${INF}Type $MNU$(basename "$0") -h$INF for help.$OFF"
	fi

	$b_interactive && return

	cfg_write
	exit "$exitval"
}

# @description Handler for user interrupt (Ctrl-C)
# @exitcode 130 Standard Ctrl-C exit code
control_c()
{
	echo -en "
	${WRN}Ctrl-c detected$INF
Cleaning up and exiting.$OFF
"
	b_interactive=false
	exitme $CTLC_EXIT
}

declare -i background=
declare -i khashsize=
declare uplog="upstream.log"
declare dnlog="downstream.log"
declare bplog="backport.log"
declare outdir=
declare updir="$PWD"
declare upcmt=
declare dncmt=
declare searchstr=
declare path=
declare repobr=
declare upscope=	# upstream scope limited to this commit expression
declare b_localus=false	# default true, upstream is in current local dir
declare b_interactive=false
declare upbase=		# the upstream commit that is the base of this
			# downstream kernel.
declare b_upeqdn=false	# Upstream commit is same as downstream commit,
			# because the downstream commit is actually
			# encompassed by the base upstream kernel (upbase).

declare myman="$MYMAN"/mkbackportlog.pgman

# Configuration (sticky) variables
declare configfile="$MYDATA"/mkbackportlog.conf
declare -A configtable
configtable[repobr]=
configtable[background]=
configtable[outdir]=
configtable[updir]=
configtable[upcmt]=
configtable[dncmt]=
configtable[searchstr]=
configtable[path]=
configtable[upscope]=
configtable[currentbranch]=

cfg_write() {
	cfg_write_cfgfile configtable
}

cfg_read() {
	cfg_read_cfgfile configtable
}

usage() {
	local usagestr

	usagestr=$(
cat <<EOF
$MNU
${UND}Patchtools v$version$OFF
$MNU
$(basename "$0") $OFF
  With no arguments invokes interactive mode.
  Type 'h' at the main menu of interactive mode for help with that.
$MNU
$(basename "$0") -od -dc -ud path [path-2 path-n] [-uc] [-us] $OFF

Create a list of commits to be backported from an upstream repo
Commits that have already been backported will have a leading$MNU #$OFF to
comment them out for subsequent processing scripts, like git-backport.

This script must be run in the downstream (RHEL) repo directory.

Creates the following files in the <outdir>.
  $STA$uplog$OFF   - contains the upstream commits since$INF upcmt$OFF
  $STA$dnlog$OFF - contains the downstream commits since$INF dwncmt$OFF
  $STA$bplog$OFF   - contains the upstream commits that have not yet been
                   backported downstream.

If all the required inputs are satisfied, you will be prompted to select an
upstream repo/branch from the list of upstream repo/branches found in your
upstream directory (see$MNU -ud$OFF switch below).$MNU$UND

Arguments$OFF$MNU
  path$OFF -$WRN This argument is REQUIRED$OFF
         A space separated list of paths and files to be searched
         for new upstream commits for the backport.
	 Can also have a$STA find$OFF expression, see example below.
	 At least one path must be given.
$MNU${UND}Switches$OFF
  $WRN${UND}Required$OFF
$MNU   -od$OFF - Directory to receive ouput files
$MNU   -dc$OFF - Downstream commit, usually the most recent RHEL commit for the
         given path(s).
         This can be a commit hash or a tag, such as$MNU RHEL-9.3.0${OFF}.
	 Required, because the script needs to now where to search in RHEL for
	 commits that have already been backported.
         The upstream commit will be extracted from this downstream commit and
	 used as the upstream start commit, unless the upstream start commit is
	 explicitly entered with the$MNU -us$OFF option below.
$MNU  ${UND}Optional$OFF
$MNU   -us$OFF - Upstream start commit. Without this switch, the script will extract the
         upstream commit from the downstream commit provided by$MNU -dc$OFF above.
	 This can be a tag, such as$MNU v6.4$OFF.
$MNU   -ue$OFF - The upstream commit where you want to end the search.
         This argument will usually be an upstream tag, e.g.$MNU v6.7$OFF
	 but it can also be an upstream commit hash.
	 All commits occuring after this commit will have a leading
	 "${MNU}#+ $OFF" prepended to their lines in the backport.log. Scripts like
	 like git-backport will ignore lines with a leading "${MNU}#$OFF", and the
	 "${MNU}+ $OFF" is added to inform that this commit is outside the scope of
	 the search.
$MNU   -ud$OFF - Directory having the upstream repo,
         Without this switch, the script expects a remote upstream repo
	 in the current$MNU \$PWD: $STA$PWD$OFF
         If there is no upstream repo declared with the "${MNU}-ud$OFF" switch
	 and no remote one in the current$MNU \$PWD$OFF, then this script will exit
	 with an error message.
  $MNU${UND}Informational$OFF
  $MNU -V $OFF - show patchtools version and exit
  $MNU -h $OFF - this help text

$MNU${UND}Example:$OFF
$INF  $(basename "$0") \\\

	-dc 975a8302ed36 \\\

        -us v6.4 \\\

	-ue v6.6 \\\

        -od ../backports/perf \\\

        -ud /work/linux/kernel \\\

        drivers/perf arch/arm64/include/asm/apple_m1_pmu.h \\\

	\$(find arch/arm64/kernel | grep perf) \\\

	\$(find include/linux | grep perf)
$OFF
Output files will be written to$INF ../backports/perf$OFF.
${INF}975a8302ed36$OFF is the hash for RHEL-9.3.0 in centos-9-stream. Commits
involving the listed files are written to the$INF downstream.log$OFF file.
Upstream commits, starting from$INF v6.4$OFF ending at$INF v6.6$OFF in $INF/work/linux/kernel$OFF,
are written to the$INF upstream.log$OFF file.
The$INF backports.log$OFF file will have the upstream commits, but with those already
downstream having a leading$INF #$OFF. Commits beyond$INF v6.6$OFF will have a leading$INF #+$OFF.
$OFF
\0
EOF
)
	echo -en "$usagestr" | more
	return 0
}

# @description Validate and return a pathname
# @arg $1 string Optional -r flag for realpath
# @arg $2 string Path to verify
# @arg $3 string-ref Variable to receive validated path
# @exitcode 0 Path valid
# @exitcode * Exits if path invalid
get_pathopt() {
	local b_real=false
	[[ "$1" == "-r" ]] && b_real=true && shift
	local path="$1"
	local -a pathary=( $path )
	local -a  pary=()
	local -n optname="$2"

	for p in ${pathary[@]}; do
		[ -e "$p" ] || exitme $exit_invpath "$path"
		$b_real && p="$(realpath "$p")"
		pary+=( "$p" )
	done

	optname="${pary[@]}"
	return 0
}

# @description Replace commas with spaces in variable list
# @arg $1 string Variables separated by commas
# @arg $2 string-ref Variable to receive space-separated string
# @exitcode 0 Always succeeds
get_varopt() {
	local var="$1"
	local -n varname="$2"

	varname="${var//,/ }"
	return 0
}

# @description Check if argument requests help
# @arg $1 string String to check for help request
# @exitcode 0 Help requested (exits after showing usage)
test_help() {
	local opt="$1"

	shopt -s nocasematch
	[[ $opt =~ (h|help) ]] && { usage; exitme $exit_ok; }
	shopt -u nocasematch
	return 0
}

# @description Validate an upstream commit expression
#   Breaks expression on double-dot and validates each commit.
# @arg $1 string Commit expression to validate
# @set updir string Upstream repo directory (read)
# @exitcode 0 Valid expression
# @exitcode * Exits if invalid
is_validcmtexpr() {
	local tmp="$1"
	local -a cary=()
	local c
	local errstr=
	local stat

	ui_cd "$updir"
	cary=(${tmp//../ })

	for c in ${cary[@]}; do
		errstr="$(git rev-parse $c 2>&1 > /dev/null)"
		stat=$?
		((stat == 0)) || exitme "$exit_invhash" "$errstr\n$c"
	done

	ui_cd -
	return 0
}

# @description Print the number of characters in kernel hash
# @set updir string Upstream kernel directory (read)
# @stdout Hash size as integer
# @exitcode 0 Always succeeds
get_khashsize() {
	local cmt

	ui_cd "$updir"
	cmt="$(gitnice -1 | cut -d' ' -f1)"
	echo "${#cmt}"
	ui_cd -
}

# @description Validate commit expression from command line
# @arg $1 string Commit expression
# @arg $2 string Switch name for error message
# @arg $3 string Variable to receive validated expression
# @exitcode 0 Valid commit
# @exitcode * Exits if invalid
getcmt() {
	local tmp="$1"
	local op="$2"
	local -n cmtname="$3"
	local -i stat=0

	is_validcmtexpr "$1"
	stat=$?

	((stat == 0)) || exitme $stat "$op $tmp"

	cmtname="$tmp"
	return 0
}

# @description Parse input options for non-interactive command line
# @arg $@ All command line arguments
# @set outdir string Output directory
# @set updir string Upstream directory
# @set path string Paths to search
# @set configtable array Config variables
# @exitcode 0 Options parsed successfully
parseops() {
	local arg=
	local opt=
	path=	# must init the path var, because it is aggregated.

	while (($# > 0)); do
	    arg="$1"

	    if [ "${arg:0:1}" == '-' ]; then
		opt="${arg:1}"

		shift
		case "$opt" in
		    ud ) get_pathopt -r "$1" updir
			 b_localus=false
			 ;;
		    od ) get_pathopt -r "$1" configtable[outdir]
			;;
		    dc ) getcmt "$1" "$arg" configtable[dncmt]
			 ;;
		    us ) getcmt "$1" "$arg" configtable[upcmt]
			 ;;
		    ue ) getcmt "$1" "$arg" configtable[upscope]
			 ;;
		    ub ) select_remote
			 ;;
		    S  ) get_varopt "$1" configtable[searchstr]
			 ;;
		    V  ) echo "Patchtools v$version"
			 exit 0
			 ;;
		    *  ) echo "unrecognized option $arg"
			 echo -e "$usagestr"
			 exit 127
		esac

	    elif [ -e "$arg" ]; then
			path="$path $arg"
	    fi

	    shift
	done

	configtable[path]="${path##*( )}"
	cfg_write
	return 0
}

# @description Create backport.log by comparing upstream/downstream commits
#   Marks already-backported commits with leading #
# @set bplog string Backport log filename
# @set uplog string Upstream log filename
# @set dnlog string Downstream log filename
# @set outdir string Output directory
# @stdout Progress output
# @exitcode 0 Always succeeds
compare_strings() {
	local uppath="$outdir/$uplog"
	local dnpath="$outdir/$dnlog"
	local chpath="$outdir/$bplog"
	local savedifs="$IFS"
	local upstr=
	local rhstr=
	local up	# one line from the upstream log
	local tmp
	local b_match=false
	local j		# upstr index
	local k		# rhstr index
	local rhcmt=

	# Instead of reading from the file, which limmits our debug
	# capabilites, create an array out of the lines in the file.
	# Set IFS to newline and then restore it after creating the
	# string arrays.
	#
	IFS=$'\n'
	upstr=($(< "$uppath"))
	rhstr=($(< "$dnpath"))
	IFS="$savedifs"

	# Zero the backport log file.
	:> "$chpath"

	for ((j = 0; j < ${#upstr[@]}; ++j)); do
		up=${upstr[j]}
		upcmt="${up:0:$khashsize}"

		for ((k = 0; k < ${#rhstr[@]}; ++k)); do
			tmp=$(echo "${rhstr[k]}" | cut -d' ' -f1)
			rhcmt="${tmp:0:$khashsize}"

			[[ "$rhcmt" == "$upcmt" ]] && {
				b_match=true
				break
			}
		done

		$b_match && echo "# $up" >> "$chpath" || echo "$up" >> "$chpath"
		$b_match && echo "# $up" || echo "$up"
		b_match=false
	done
	return 0
}

# @description Initialize sticky variables and environment
# @set configfile string Config file path
# @set configtable array Config variables
# @set MYDATA string Data directory path
# @exitcode 0 Always succeeds
init_env() {
	local bgtemp

	[ -d "$MYDATA" ] || mkdir -p "$MYDATA"

	ui_setbg bgtemp

	cfg_start configtable "$configfile"
	background="$bgtemp"
	configtable[background]="$background"
	currentbranch=$(get_currentbranch)
	configtable[currentbranch]="$currentbranch"
	cfg_write
	return 0
}

# @description Notify user if logfile already exists
# @arg $1 string Logfile path to check
# @stdout Warning if file exists
# @exitcode 0 Always succeeds
check_log() {
	log="$1"

	echo -e "${INF}Create : $STA$log$OFF"

	[ -f "$log" ] && {
		echo -en "$WRN$log exists.$OFF "
		echo -e "${INF}It will be overwritten if you continue.$OFF"
	}
	return 0
}

# @description Echo the current git branch
# @stdout Current branch name
# @exitcode 0 Always succeeds
get_currentbranch() {
	git branch | grep -E '^\*' | cut -d' ' -f2
}

# @description Search for string in commits from upstream.log
# @set updir string Upstream directory (read)
# @set outdir string Output directory (read)
# @set bplog string Backport log filename (read)
# @stdout Matching commits
# @exitcode 0 Always succeeds
seek_str() {
	local prepend=
	local outfile=
	local commit
	local str

	ui_cd "$updir"
	for str in $searchstr; do
		prepend=$(echo "$str" | cut -d' ' -f1)
		outfile="$outdir/$prepend-$bplog"

		echo -e "\n${STA}Creating $outfile$INF"
		: > "$outfile"
		while read -r line; do
			[ "${line:0:1}" == "#" ] && continue
			commit=$(echo "$line" | cut -d' ' -f1)
			git show "$commit" | grep -q -m1 "$str" || continue
			echo "$line" | tee -a "$outfile"
		done < "$outdir/$bplog"
	done
	ui_cd -
	return 0
}

# @description Choose from available repo/branches in current directory
# @set updir string Upstream directory (read)
# @set repobr string Selected repo/branch (written)
# @set configtable array Config variables (written)
# @stdout Branch selection menu
# @exitcode 0 Branch selected
# @exitcode 1 No remote upstream repo found
select_remote() {
	local brstr=
	local brancharray=()

	# Get all the branches into one string

	if [[ "$updir" != "$PWD" ]]; then
		ui_cd "$updir"
		brstr=$(git branch -r)
		ui_cd -
	else
		# We have a remote in PWD
		# Skip all the remotes that are from the origin or $USER.
		# We are only interested in upstream remotes in PWD
		brstr=$(git branch -r | grep -E -v "origin|$USER")
	fi

	# Filter out lines with '-> in them, because they are not branches
	while read -r s; do [[ $s == *"->"* ]] || brancharray+=("$s"); done <<< "$brstr"

	if [ -z "$brstr" ]; then
		echo -e "${WRN}There is no remote upstream repo in directory: $STA$updir$OFF"
		return 1
	fi

	if [ ${#brancharray[@]} -gt 1 ]; then
		echo -e "\n$UND${MNU}Select the upstream repo/branch$OFF"
		select_from_array brancharray "branches" repobr
	else
		repobr=${brancharray[0]}
		echo -e "$INF Only one upstream branch in this repo: $STA$repobr$OFF"
		echo -e "$INF Nothing else to choose from.$OFF"
	fi

	configtable[repobr]="$repobr"
	return 0
}

# @description Choose from available local branches
# @set currentbranch string Selected branch (written)
# @set configtable array Config variables (written)
# @stdout Branch selection menu
# @exitcode 0 Always succeeds
select_localbr() {
	local -a branches=()

	# This git command prints the branches without decoration, since
	# there is no porcelain switch for git branch.
	mapfile -t branches <<< $(git for-each-ref --format='%(refname:short)' refs/heads/)

	if ((${#branches[@]} > 1)); then
		echo -e "\n$UND${MNU}Select the lcal branch$OFF"
		select_from_array branches "branches" currentbranch
	else
		echo -e "$INF Only one branch in this repo: $STA$currentbranch$OFF"
		echo -e "$INF Nothing else to choose from.$OFF"
	fi

	git checkout "$currentbranch"
	configtable[currentbranch]="$currentbranch"
	return 0
}

# @description Limit backport log to commits before upscope
#   Comments out commits beyond scope with '#+ ' prefix.
# @set outdir string Output directory (read)
# @set bplog string Backport log filename (read)
# @set upscope string Limiting upstream commit (read)
# @stdout Modified backport log
# @exitcode 0 Always succeeds
limit_scope() {
	local delim=
	local line
	local -a linary=()
	local outfil="$outdir"/"$bplog"

	mapfile -t linary < "$outfil"
	> "$outfil"

	for (( i = 0; i < ${#linary[@]}; ++i)) ; do
		local tmpstr=
		local -a tmpary=()
		local cmt=
		local line="${linary[i]}"

		([ ${line:0:1} == "#" ] || [ ${line:0:1} == "+" ]) && continue

		# tokenize the line on spaces by excluding double quotes inside
		# array parens.
		tmpary=( $line )
		cmt="${tmpary[0]}"
		tmpstr="$(gitnice -1 --no-merges "$upscope"^.."$cmt")"

		[ -n "$tmpstr" ] && linary[i]="#+ $line"
	done

	echo -e "$INF"
	printf "%s\n" "${linary[@]}" | tee -a "$outfil"
	echo -e "$OFF"
	return 0
}

# @description Display current user-supplied paths
# @set configtable array Config with path (read)
# @stdout Formatted path list
# @exitcode 0 Always succeeds
show_paths() {
	local -a pthary=()
	local -i pad=32
	local padstr
	local path="${configtable[path]}"

	[ -z "$path" ] && { echo -e "\n "; return; }

	padstr="$(ui_rptchr ' ' $pad)"
	pthary=( $path )

	echo -e "$STA${pthary[0]}"
	printf "$padstr%s\n" ${pthary[@]:1}
}

# @description Test if all required parameters are present
# @set configtable array Config variables (read)
# @set exitmsgary array Exit messages (read)
# @stdout Warning for missing parameters
# @exitcode 0 All required parameters present
# @exitcode 1 Some parameters missing
test_reqparms() {
	local -i stat=0
	[ -n "${configtable[updir]}"  ] || { stat=1; echo -e "$WRN${exitmsgary[exit_noupdir]}"; }
	[ -n "${configtable[outdir]}" ] || { stat=1; echo -e "$WRN${exitmsgary[exit_nooutd]}"; }
	[ -n "${configtable[path]}"   ] || { stat=1; echo -e "$WRN${exitmsgary[exit_nopath]}"; }
	[ -n "${configtable[repobr]}" ] || { stat=1; echo -e "$WRN${exitmsgary[exit_norepobr]}"; }
	[ -n "${configtable[dncmt]}"  ] || { stat=1; echo -e "$WRN${exitmsgary[exit_nodncmt]}"; }
	((stat == 0)) || ui_press_any
	return $stat
}

# @description Clear all config parameters
# @set configtable array Config variables (cleared)
# @exitcode 0 Always succeeds
clear_parms() {
	local key

	for key in "${!configtable[@]}"; do
		key=${key// /}
		configtable["$key"]=
	done
}

# @description Display the upstream directory
# @set configtable array Config with updir (read)
# @set b_localus bool Upstream in PWD flag (read)
# @stdout Upstream directory path
# @exitcode 0 Always succeeds
show_upstreamdir() {
	$b_localus && echo -n -e "${INF}default is PWD: "
	echo -e -n $STA${configtable[updir]}$OFF
	return 0
}

# @description Delete search paths from the list interactively
# @arg $1 string Variable name holding path string (by reference)
# @stdout Path selection menu
# @exitcode 0 Always succeeds
delete_paths() {
	local -n dp_path="$1"
	local -a pathary=()
	local -i patharysiz=
	local sel=

	pathary=( $dp_path )
	patharysiz=${#pathary[@]}

	if ((patharysiz >= 1)); then
		echo -e "\n$UND${MNU}Select the path(s) to delete$OFF"
		echo -e "${MNU}Press $qstr when you're done.$OFF"

		while ((patharysiz >=1)); do
			for((i = 0; i < $patharysiz; ++i)); do
				printf "$MNU%2s. $OFF" "$((i + 1))"
				echo "${pathary[i]}"
			done

			if loop_range_q 1 "$patharysiz" sel; then
				((--sel))
				unset pathary[sel]
				pathary=( ${pathary[@]} )
				patharysiz=${#pathary[@]}
				((patharysiz < 1)) && {
					echo -e "${WRN}No more paths to delete!$OFF"
					break
				}
			else
				break
			fi
		done
	else
		echo -e "${INF}There are no paths to delete.$OFF"
	fi
	dp_path="${pathary[@]}"
	return 0
}

# @description Display the interactive user menu
# @set configtable array Config variables (read)
# @stdout Menu display
# @exitcode 0 Always succeeds
show_menu() {
	local mbl_menu
	local addpath=

	local mbl_menu=$(
cat <<EOF
$MNU$UND
mkbackportlog - patchtools: $STA$version$OFF
$MNU$UND
Required$OFF
$MNU o$OFF - Output Directory         : $STA${configtable[outdir]}$OFF
$MNU u$OFF - Upstream repo directory  : $(show_upstreamdir)
$MNU b$OFF - Upstream repo/branch     : $STA${configtable[repobr]}$OFF
$MNU d$OFF - Downstream RHEL commit   : $STA${configtable[dncmt]}$OFF
$MNU p$OFF - Path(s) to search        : $(show_paths)\
$MNU$UND
Optional$OFF
$MNU s$OFF - Start at upstream commit : $STA${configtable[upcmt]}$OFF
$MNU e$OFF - End at upstream commit   : $STA${configtable[upscope]}$OFF
$MNU B$OFF - Current Downstream Branch: $STA$currentbranch$OFF
$MNU A$OFF - Add to search path
$MNU D$OFF - Delete from search path
$MNU$UND
Functional$OFF
$MNU r$OFF - Run with the above parameters
$MNU C$OFF - Clear all parameters
$MNU q$OFF - Quit this script
$MNU h$OFF - Help
\0
EOF
)
	echo -e "$mbl_menu"
	return 0
}

# @description Parse menu input and execute action
# @arg $1 string Menu selection character
# @exitcode 0 Continue menu loop
# @exitcode 1 Run requested (break menu loop)
menu_parser() {
	local mp_in="$1"

	case "$mp_in" in
		q ) exitme $exit_ok
		    ;;
		d ) getuser "Downstream RHEL commit: " dncmt
		    is_validcmtexpr && configtable[dncmt]="$dncmt"
		    ;;
		p ) getuser "Path(s) to be searched: " path
		    get_pathopt "$path" path && {
			path=$(echo "$path" | tr '\n' ' ')
			configtable[path]="$path"
		    }
		    ;;
		A ) getuser "Additional Path(s) to be searched: " addpath
		    get_pathopt "$addpath" addpath && {
			addpath=$(echo "$addpath" | tr '\n' ' ')
			path="$path $addpath"
			configtable[path]="$path"
		    }
		    ;;
		D ) delete_paths path
		    configtable[path]="$path"
		    ;;
		o ) getuser "Directory to receive output files: " outdir
		    get_pathopt -r "$outdir" outdir && configtable[outdir]="$outdir"
		    ;;
		u ) getuser "Upstream repo directory: " updir
		    get_pathopt -r "$updir" updir && configtable[updir]="$updir"
		    [ "$updir" == "$PWD" ] && b_localus=true || b_localus=false
		    select_remote
		    ;;
		s ) getuser "Start at this upstream commit: " upcmt
		    is_validcmtexpr "$upcmt" && configtable[upcmt]="$upcmt"
		    ;;
		e ) getuser "End at this upstream commit: " upscope
		    is_validcmtexpr "$upscope" && configtable[upscope]="$upscope"
		    ;;
		b ) select_remote
		    ;;
		B ) select_localbr
		    ;;
		C ) clear_parms
		    ;;
		r ) test_reqparms && return 1
		    ;;
		h ) ptpage -b $background "$myman"
	esac

	return 0
}

# @description Main menu loop for interactive mode
# @exitcode 0 User selected run
menu_loop() {
	local menuin

	while :; do
		cfg_read
		show_menu
		promptgetchar "${MNU}Enter one of the above: $OFF" menuin
		# If all required params are there and user pressed 'r',
		# then break and run
		menu_parser $menuin || break
		cfg_write
	done
	return 0
}

# @description Execute with current parameters to create backport logs
# @set outdir string Output directory (read)
# @set updir string Upstream directory (read)
# @set uplog string Upstream log filename
# @set dnlog string Downstream log filename
# @set bplog string Backport log filename
# @set repobr string Repo/branch (read)
# @set path string Paths to search (read)
# @set upcmt string Upstream commit (read/written)
# @set upscope string Scope limit commit (read)
# @stdout Progress and log output
# @exitcode 0 Success
run() {
	# If the user did not input an upstream commit, then extract the
	# upstream commit from the submitted RHEL commit, which is the most
	# recent RHEL commit under consideration, entered with the -dc option.
	# If the submitted RHEL commit does not have a corresponding upstream
	# commit, then it may be contained within the upstream base commit for
	# this RHEL kernel. In that case, upcmt=dncmt.
	# If none of those criteria are met, then exit with error messages.
	if [ -z "$upcmt" ]; then
		upcmt="$(oneup $dncmt)" || {
			git rev-list "$upbase" | grep -q -m1 "$dncmt" \
			&& upcmt="$dncmt" \
			|| exitme "$exit_invhash" "$dncmt"
		}

		# validate the $upcmt
		[[ $upcmt =~ ^[0-9A-Fa-f]+$ ]] || exitme $exit_invhash "$upcmt"
		is_validcmtexpr "$upcmt" || exitme $exit_invhash "$upcmt"

		# If the upcmt is the base kernel tag, then no need to trim
		# the upcmt to kernel short hash size.
		[ "$upcmt" == "$upbase" ] || upcmt="${upcmt:0:$khashsize}"
		configtable[upcmt]="$upcmt"
	fi

	read -r mainbranch <<< "$(git branch -r | grep origin/HEAD | cut -d'>' -f2)"

	check_log "$outdir/$uplog"
	check_log "$outdir/$dnlog"
	check_log "$outdir/$bplog"

	echo -e "${INF}Upstream branch       : $STA$repobr$OFF"
	echo -e "${INF}Upstream Start commit : $STA$upcmt$OFF"
	[ -n "$upscope" ] && 	echo -e "${INF}Upstream End Commit   : $STA$upscope$OFF"
	# echo -e "${INF}Downstream branch     : $STA$mainbranch$INF"
	echo -e "${INF}Downstream branch     : $STA$currentbranch$INF"

	if [ -n "$path" ]; then
		# If there's more than one path, show them all.
		if (($(wc -w <<< "$path") > 1)); then
			echo -e "${INF}Paths:$OFF"
			# shellcheck complains about vars without quotes, but
			# sometimes, it's what you really want.
			printf "  %s\n" $path
		else
			echo -e "${INF}Path:$OFF $path"
		fi
	fi

	echo
	echo -en "${CAU}Press any key to proceed or CTRL-C to exit...$OFF"
	read -r -n1

	echo -e "$STA$PWD$OFF"
	echo -e "${STA}Creating $outdir/$uplog$INF"

	# Get the list of upstream commits starting from the one provided
	# as the upstream start or the one extracted from the submitted
	# RHEL commit with the -dc option.
	ui_cd "$updir"
	gitnice -r -c -d --no-merges \
		"$upcmt^..$repobr" $path 2>&1 | tee "$outdir/$uplog"
	echo
	ui_cd -
	echo -e "$STA$PWD$OFF\n"
	echo -e "${STA}Creating $outdir/$dnlog$INF"

	> "$outdir/$dnlog"
	while read line; do
		local tuc="$(cut -d' ' -f1 <<< "$line")" # upstream commit hash
		local upd="$(cut -d' ' -f3 <<< "$line")" # date of upstream commit

		# First check if this upstream commit is part of the base kernel
		# that the downstream repo was created from (e.g., v6.6). If so,
		# it's already downstream as part of the original kernel base.
		# This is faster than searching commit messages.
		if git -C "$updir" merge-base --is-ancestor "$tuc" "$upbase" 2>/dev/null; then
			echo "$line" | tee -a "$outdir/$dnlog"
			continue
		fi

		# Search for downstream commits that reference this upstream commit
		# in their commit message (standard for cherry-picked/backported commits).
		# If found, write the upstream commit line to downstream.log so that
		# compare_strings can match it against upstream.log.
		if git log --oneline --grep="$tuc" --since="$upd" -- $path 2>/dev/null | grep -q .; then
			echo "$line" | tee -a "$outdir/$dnlog"
		fi
	done < "$outdir/$uplog"

	echo
	echo -e "${STA}Creating $outdir/$bplog$INF"
	compare_strings

	[ -n "$searchstr" ] && seek_str
	echo -e "$OFF"

	if [ -n "$upscope" ]; then
		limit_scope & mypid=$!
		ui_waitonproc_tty $mypid .05 "Limiting scope to $MNU$upscope$OFF. Please wait."
	fi
	return 0
}

# @description Extract upstream base kernel version from downstream tags
# @set upbase string Upstream base version (e.g., v6.6)
# @exitcode 0 Always succeeds
extract_upbase() {
	local ktag=

	# Get the most recent RHEL kernel tag
	ktag="$(git tag --list 'kernel-*' --sort=-v:refname | head -n 1)"

	# Now extract the upstream base kernel version from the rhel
	# kernel tag.
	#
	upbase="$(cut -d'-' -f2 <<< "$ktag")"
	upbase="$(cut -d. -f1-2 <<< "$upbase")"
	upbase="v${upbase}"
	return 0
}

# @description Main entry point
# @arg $@ Command line arguments
# @exitcode 0 Success
main() {
	local mainbranch
	local currentbranch
	local mypid

	init_env

	# Get the short size of the upstream kernel hashes.
	khashsize=$(get_khashsize)

        # Trap for control-c
        trap control_c SIGINT

	extract_upbase

	if (($# == 0 )); then
		b_interactive=true

		while :; do
			menu_loop
			run
		done
	else
		b_interactive=false
		test_help "$1"
		parseops "$@"

		[ -f .git/config ] || exitme $exit_norepo "PWD: $PWD"

		# If user did not supply the upstream repo dir in the options, and
		# there is no upstream repo in $PWD/.git/config, then exit with
		# help clue.
		if [ -z "$updir" ]; then
			git branch -r | grep -E -v "origin|$USER" ||
				exitme $exit_noupstream "PWD: $PWD"
			updir="$PWD"
			configtable[updir]="$PWD"
		fi

		[[ "$updir" == "$PWD" ]] && b_localus=true || b_localus=false

		# update the configfile before going any further
		cfg_write

		select_remote repobr
		currentbranch=$(get_currentbranch)
		configtable[currentbranch]="$currentbranch"
	fi

	run

	exitme $exit_ok
}

main "$@"

exitme $exit_ok

