#!/bin/bash
#
# mkrepos

[ -n "$MYDIR" ] || {
        declare MYDIR=
        MYDIR="$(dirname "$(readlink -f "$0")")"
}

[ -n "$MYLIB" ] || {
        declare MYLIB=
        MYLIB="${MYDIR}/lib"
}

[ "$ui_loaded" ] || source "${MYLIB}/ui.source"

declare -i termbkgnd=

declare repolist=
declare b_host=false
declare usagestr=


export_usagestr() {
	usagestr="$(
cat <<EOF

${INF}$(basename $0) <host | all>${OFF}

${CAU}NOTE:${OFF}
   ${STA}GITLAB_TOKEN ${INF}must be set to a valid GitLab personal access token.

   ${MNU}$ ${INF}export GITLAB_TOKEN="<${STA}your gitlab token${INF}>${OFF}"

${MNU}Description:${OFF}
   Create the upstream and downstream kernel repo(s)
   Repos will be created in the /work directory, as follows.
      /work/upstream/kernel
      /work/7/kernel
      /work/8/kernel
      /work/9/kernel
      /work/10/kernel
      /work/c9s/kernel
      /work/c10s/kernel
      /work/ark/kernel

${MNU}Arguments:${OFF}
   all  - creates all the RHEL repos listed above.
   host - clones only the downstream kernel repo for the major
          version of the host system.

	 For example, on a RHEL-9 or CentOS-9 system...

		$ mkrepos host

	...will only clone the following repos,

	/work/upstream/kernel
	/work/c9s/kernel
	/work/9/kernel
\0
EOF
)"
	export usagestr
}

declare distro=
declare majversion=

usage() {
	echo -e "$usagestr"
	exit 1
}

#** control_c: control-c trap
#
# Global
#   CTLC_EXIT - bash environment variable
#*
control_c() {
        echo -e "\n${CAU}Ctrl-c detected\n${INF}Cleaning up and exiting.$OFF"
        exit $CTLC_EXIT
}

mkrepo() {
	local mr_distro="$1"
	local majver="$2"
	local reponam
	local repodir
	local repo

	if [ "$mr_distro" == "rhel" ]; then
		reponam="/rhel-$majver"
		repodir="/work/$majver"
		repo="git@gitlab.com:redhat/rhel/src/kernel/rhel-${majver}.git"

	elif [ "$mr_distro" == "centos-stream" ] || [ "$mr_distro" == "centos" ]; then
		reponam="centos-stream-$majver"
		repodir="/work/c${majver}s"
		repo="git@gitlab.com:redhat/centos-stream/src/kernel/centos-stream-${majver}.git"

	elif [ "$mr_distro" == "kernel-ark" ]; then
		reponam="kernel-ark"
		repodir="/work/ark"
		repo="git@gitlab.com:cki-project/kernel-ark.git"
	else
		echo -e "$CAU$mr_distro is not supported by this script.$OFF"
		return
	fi

	[ -d "$repodir" ] || mkdir -p "$repodir"
	cd "$repodir" || { echo -e "${CAU}Cannot cd into $STA$repodir$OFF"; exit 1; }

	if [ -f kernel/.git/config ] ; then
		echo -e "$CAU$PWD/kernel repo $STA$repodir/$reponam$CAU already exists.$OFF"
		return
	else
		echo -e "${CAU}Cloning $repo into $repodir/kernel...$OFF"
		if ! git clone "$repo" kernel; then
			echo -e "${CAU}Failed to clone $repo$OFF"
			echo -e "${INF}Please verify:$OFF"
			echo -e "  ${MNU}1.${INF} Your SSH key is uploaded to GitLab$OFF"
			echo -e "  ${MNU}2.${INF} You have access to the repository$OFF"
			return 1
		fi
		cd kernel || { echo -e "${CAU}cannot cd into $STA$PWD/$repodir$OFF"; exit 1; }
		git fetch
		git pull
		git remote add tcamuso git@gitlab.com:tcamuso/"$distro-${majver}.git"
		echo "$PWD" >> "$repolist"
	fi
}

create_upstream() {
	[ -d /work/upstream ] || mkdir -p /work/upstream
	cd /work/upstream || { echo -e "${CAU}Cannot cd into /work/upstream$OFF"; return 1; }

	if [ -f kernel/.git/config ]; then
		echo -e "\n${CAU}Upstream kernel already present.$OFF\n"
		return
	fi

	echo -e "${INF}Cloning upstream kernel...${OFF}"
	if ! git clone \
		git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git \
		kernel; then
		echo -e "${CAU}Failed to clone upstream kernel$OFF"
		return 1
	fi

	cd kernel || { echo -e "${CAU}Cannot cd into kernel$OFF"; return 1; }

	git remote add gh-ipmi https://github.com/cminyard/linux-ipmi.git
	git remote add net-next \
		https://git.kernel.org/pub/scm/linux/kernel/git/netdev/net-next.git
	git remote add scsi \
		https://git.kernel.org/pub/scm/linux/kernel/git/jejb/scsi.git
	git remote add power \
		https://git.kernel.org/pub/scm/linux/kernel/git/powerpc/linux.git
	git remote add perf \
		https://git.kernel.org/pub/scm/linux/kernel/git/jolsa/perf.git
	git remote add linux-rt-devel \
		https://git.kernel.org/pub/scm/linux/kernel/git/rt/linux-rt-devel.git
	git remote add crypto \
		https://git.kernel.org/pub/scm/linux/kernel/git/herbert/cryptodev-2.6.git
	git remote add bluetooth \
		git://git.kernel.org/pub/scm/linux/kernel/git/bluetooth/bluetooth-next.git
	git fetch -p --all
	echo "/work/upstream/kernel" >> "$repolist"
}

create_downstream() {
	mkrepo "rhel" "7"
	mkrepo "rhel" "8"
	mkrepo "rhel" "9"
	mkrepo "rhel" "10"
	mkrepo "centos-stream" "9"
	mkrepo "centos-stream" "10"
	mkrepo "kernel-ark"
}

get_distro() {
	[ -f /etc/os-release ] || { echo -e "\n${CAU}/etc/os-release does not exist!$OFF"; exit 1; }
	foo=$(grep -w 'ID' /etc/os-release | cut -d"=" -f2)

	# Strip off the double quote marks
	#
	foo=${foo%\"}
	foo=${foo#\"}

	# distro is the lowercase of the ID we pulled out of /etc/os-release
	#
	distro=$(echo "$foo" | tr '[:upper:]' '[:lower:]')

	echo "Distro: $distro"

	if [[ "$distro" == "rhel" ]] || [[ "$distro" == "centos" ]]; then
		# Get the major version and strip off any leading double quotes
		#
		majversion=$(grep -w 'VERSION_ID' /etc/os-release | cut -d= -f2 | cut -d. -f1)
		majversion=${majversion#\"}
		majversion=${majversion%\"}

		echo "majversion: $majversion"
	elif [[ "$distro" != "fedora" ]]; then
		echo -e "\n$CAU$distro is not a distro supported by this script.$OFF"
		exit 1
	fi
}

#** init
#
# Global
#*
init() {
        ui_setbg termbkgnd
}

#** main
#*
main() {
        # Trap for control-c
        trap control_c SIGINT

	init
	export_usagestr

	# Require GITLAB_TOKEN
	if [[ -z "${GITLAB_TOKEN}" ]]; then
		echo -e "${CAU}GITLAB_TOKEN is not set.{$OFF}"
		echo -e "${INF}Please export your GitLab personal access token, e.g.:${OFF}"
		echo -e "   ${MNU}$ ${INF}export GITLAB_TOKEN=your_token_here${OFF}"
		exit 1
	fi

	# No arguments or help flags → usage
	if [[ $# -eq 0 ]]; then
		usage
		exit 1
	fi

	case "$1" in
		-h|--help|help)
			usage
			exit 0
			;;
		all)
			echo -e "\n${INF}Creating all repos...${OFF}"
			b_host=false
			;;
		host)
			echo -e "\n${INF}Creating host‑specific repos...${OFF}"
			b_host=true
			;;
		*)
			echo -e "\n${CAU}Unknown argument: ${MNU}${1}${OFF}"
			usage
			exit 1
			;;
	esac

	local pr_cfg_dir="$HOME/.config/patchreview"

	repolist="${pr_cfg_dir}/repolist"

	# Ensure required directories exist
	[ -d /work ] || {
		echo -e "${CAU}There is no /work directory.$OFF"
		exit 1
	}
	[ -d "$pr_cfg_dir" ] || mkdir -p "$pr_cfg_dir"
	# Ensure ~/.ssh directory exists with correct permissions
	mkdir -p "$HOME/.ssh"
	chmod 700 "$HOME/.ssh"
	[ -f "$HOME/.ssh/known_hosts" ] || touch "$HOME/.ssh/known_hosts"

	# Add GitLab to known_hosts BEFORE any SSH operations to prevent
	# interactive prompts asking about host authenticity
	echo -e "${INF}Adding gitlab.com to SSH known_hosts...${OFF}"
	ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts 2>/dev/null

	# Set GIT_SSH_COMMAND to disable strict host key checking for any
	# hosts not yet in known_hosts (belt and suspenders approach)
	export GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=accept-new -o BatchMode=yes"

	# Upload SSH key to GitLab (requires GITLAB_TOKEN)
	echo -e "${INF}Uploading SSH key to GitLab...${OFF}"
	if ! gitlab-upload-sshkey; then
		echo -e "${CAU}gitlab-upload-sshkey failed$OFF"
		echo -e "${INF}Please verify your GITLAB_TOKEN is valid and has 'api' scope.$OFF"
		exit 1
	fi

	cd /work

	> "$repolist"
	get_distro
	create_upstream

	if $b_host; then
		mkrepo "$distro" "$majversion"
		[[ "$distro" == "rhel" ]] && ((majversion > 8)) && \
			mkrepo "centos-stream" "$majversion"
	else
		create_downstream
	fi

	[ -d "$HOME"/.cache ] || mkdir "$HOME"/.cache
	crontab - << EOF
0 7 * * * date > /work/crontab-repotask; /home/tcamuso/bin/repotask >> /work/crontab-repotask
EOF
}

main $@

exit 0

