#!/bin/bash
#
# Create an empty bash script with placeholders for help text and
# a usage function
#

if [ -f "$1" ]; then
	echo
	echo "File $1 already exists!"
	echo
	exit 1
fi

usagestr=$(
cat <<EOF

$(basename $0) <bashscript>

Create an empty bash script with placeholders for help text and
a usage function

\\0
EOF
)

usage() {
	echo -e "$usagestr"
	exit
}

[ $# -eq 1 ] || usage

echo -e '#!/bin/bash
#
# '"$1"'
#

usagestr=$(
cat <<EOF

$(basename $0)

\\0
EOF
)

usage() {
	echo -e "$usagestr"
	exit
}

[ $# -gt 0 ] || usage
' >> $1

chmod +x "$1"
