#!/bin/bash
#
# nicspeed
#

declare usagestr=$(
cat <<EOF

$(basename $0) nic

  Print the speed of a network interface to stdout

  nic - the network interface whose speed we want to know

\0
EOF
)

usage() {
	echo -e "$usagestr"
	exit $1
}

argcount=1

[ $# -eq  $argcount ] || usage 1

echo "cat /sys/class/net/"$1"/speed"
cat /sys/class/net/"$1"/speed

