#!/bin/bash
#
# patchdevelop - based on patchreview

# This script assumes that you have already extracted your patches into
# the directory named as "indir" below. Only files named "*.patch" will
# be considered.
#
# To create a patch set from email ...
# In mutt, tag the thread you want to extract with esc-t. Untag the
# prologue, as it's not a patch. Then extract the thread into text
# files using ;-esc-C (uppercase C). When prompted for the directory,
# type the name of the mailbox directory or uparrow to the previous
# save.
#
# This script can also be used to compare any two patch sets.

# Calls on the following external scripts.
#
# ./githead
# ./patcmp
# ./patbatcmp
# ./patbatcmpmgr
#
# Requires to run ...
#
# ./lib/*.source
# ./.data/patchreview.prj
# ./man/patchreview.man

#######################################
# Default file locations
#######################################
#
# Whatever directory this script and its companions are located in
# must be in the executable path.
#
# export PATH=$PATH:MYDIR
#
# Where MYDIR is the directory in which this script and its companions
# are located.
#
declare MYDIR=$(dirname $(which $(basename $0)))
declare MYLIB=$MYDIR/lib

#######################################
# External Source Files
#######################################
source $MYLIB/ui.source
source $MYLIB/project.source
source $MYLIB/gitutilities.source
source $MYLIB/patch-common.source

#########################################
# Functions
#########################################

function init_booleans {
	b_prologue=false

	[ $index -eq 0 ] && return
	for ((index=boolindex; index <= prj_entries; index++)); do
		prj_set_item $index true
	done
}

# get_booleans
#
# Read the values of the program flow control booleans from the
# project file.
#
# removed in v4.4
# 	b_patcmp
# 	b_patbatcmp
#
# added in v4.4
# 	b_40digit
#
# removed in v5.0
#	b_apply_patches
#
# removed in v7.0
# 	b_save_githead
# 	b_gitam_err_abort
#
# removed in v9.0
#	b_40digit
#
# added in v9.0
#	b_extmenu
#
# removed in v9.1
# 	b_extmenu
#
function get_booleans {
	[ $boolindex -eq 0 ] && return
	index=$boolindex
	for bool in \
	b_rename_infiles \
	b_fmt_upstream
	do
		eval $bool=$(prj_get_item $index)
		ui_digit2bool $bool
		let index++
	done
}


# set_booleans
#
# Write the current values of the program flow booleans into the
# project file.
#
# removed in v4.4
# 	b_patcmp
# 	b_patbatcmp
#
# added in v4.4
# 	b_40digit
#
# removed in v5.0
#	b_apply_patches
#
# removed in v7.0
# 	b_save_githead
# 	b_gitam_err_abort
#
# removed in v9.0
#	b_40digit
#
# added in v9.0
#	b_extmenu
#
# removed in v9.1
# 	b_extmenu
#
function set_booleans {
	[ $boolindex -eq 0 ] && return
	index=$boolindex
	for bool in \
	b_rename_infiles \
	b_fmt_upstream
	do
		prj_set_item $index ${!bool}
		let index++
	done
	b_prologue=false
	return 0
}

# show_settings - the main menu display
#
# Globals:
# 	indir
# 	outdir
# 	lasttag
# 	gitbranch
# 	infilecount
# 	patstr
# 	editor
# 	b_rename_infiles
# 	b_fmt_upstream
#
show_settings() {
	local current_head_trunc=$(get_current_head_trunc $menucols)
	local s	settingstr=$(
cat <<EOF
$MNU
    $UND\0Environment       $OFF
    Most recent tag         :$STA $lasttag$OFF
    Current Head            :$STA $current_head_trunc$OFF
$MNU b$OFF  Current git branch      :$STA $(git_getcurrentbranch)$OFF
$MNU d$OFF  $indirstr directory         :$STA $indir$OFF has$STA $infilecount$OFF $patstr\0files
$MNU w$OFF  $outdirstr directory          :$STA $outdir$OFF
$MNU e$OFF  Diff Editor             :$STA $editor$OFF
$MNU c$OFF  Toggle Colors ON/OFF    :$STA $(show_colors)$OFF
$MNU
    $UND\0Batch Run Parameters$OFF
$MNU 1$OFF  Compare mode            :$STA $(show_cmpmode)$OFF
$MNU 2$OFF  Patch apply mode        :$STA $(show_applymode)$OFF
$MNU 3$OFF  Patch apply fail mode   :$STA $(show_applyfailmode)$OFF
$MNU 4$OFF  Seek missing commits    :$STA $(show_patchseekmode)$OFF\
 $(show_nextpatch)$BLD
$MNU
    $UND\0Main Controls     $OFF
$MNU r$OFF  Run in batch mode
$MNU i$OFF  Init to defaults
$MNU h$OFF  help text
$MNU q$OFF  Quit this script
$MNU x$OFF  Toggle Extended Menu
$OFF
EOF
)
	local extmenu=$(
cat <<EOF
$BLD\
    $UND\0Discrete Operations$OFF
$MNU R$OFF  Rename mail files in    :$STA $indir$OFF
$MNU F$OFF  Format commits into     :$STA $outdir$OFF
$MNU S$OFF  Seek missing commits \
 $(show_apply_patches)$BLD
$MNU P$OFF  Compare Patches
$MNU B$OFF  Create a new branch at  :$STA $current_head_trunc$OFF\
 $(show_view_logs)$BLD
$OFF
EOF
)
	echo -e "$settingstr"
	[ $menumode -eq $menumode_ext ]  && echo -e "$extmenu"
}

menu_parser() {
	get_filecount
	show_settings
	promptgetchar ""$MNU"Enter one of the above: "$OFF"" setting

	case $setting in

		c )	toggle_colors
			;;
		b )	git_setbranch $branchlist
			git_get_lasttag lasttag $last_tag_file
			;;
		d )	prj_set_directory "$indirstr" $prj_indir indir quiet
			;;
		w )	prj_set_directory "$outdirstr" $prj_outdir outdir quiet
			;;
		e )	set_editor
			;;
		x )	ui_cycle_state menumode $menumode_states
			prj_set_item $prj_menumode $menumode
			;;
		R )	renpatfiles
			;;
		F )	format_upstream_patches
			;;
		S )	[ -f "$us_commits" ] || format_upstream_patches
			check_fixes "$us_commits"
			;;
		A )	[ $applymode -ne $applymode_off ] && ! $b_allapplied \
				&& exec_apply_patches
			;;
		V )	view_logs
			;;
		1 )	ui_cycle_state cmpmode $cmpmode_states
			prj_set_item $prj_cmpmode $cmpmode
			;;
		2 )	ui_cycle_state applymode $applymode_states
			prj_set_item $prj_applymode $applymode
			;;
		3 )	ui_cycle_state applyfailmode $applyfailmode_states
			prj_set_item $prj_applyfailmode $applyfailmode
			;;
		4 )	ui_cycle_state patchseekmode $patchseek_states
			prj_set_item $prj_patchseekmode $patchseekmode
			;;
		5 )	$b_selpat && select_patch
			;;
		i )	init_menu
			;;
		B )	create_branch
			;;
		P )	compare_patches
			;;
		q )	exit_me 0
			;;
		r )	set_booleans
			return $rc_run
			;;
		h )	less $manual
			;;
	esac
	return $rc_continue
}

# init_files
#
# Initialize the global names of the directories and files to be used
# throughout the script.
#
# Globals:
# 	prj_indir
# 	prj_outdir
# 	indirstr
# 	outdirstr
# 	indir
# 	outdir
# 	bp_commits_name
# 	us_commits_name
# 	bp_commists
# 	us_commits
# 	usvbp_commits_name
# 	usvp_commits
# 	mismatch_file
#
init_files() {

	# get the patch and work directories.
	#
	check_dir $prj_indir "$indirstr" indir
	check_dir $prj_outdir "$outdirstr" outdir
	bp_commits="$outdir/$bp_commits_name"
	us_commits="$outdir/$us_commits_name"
	usvbp_commits="$outdir/$usvbp_commits_name"
	mmfile="$outdir/$mismatch_file"
}

function menu_loop {
	get_booleans
	init_files

	# get the editor
	#
	editor=$(prj_get_item $prj_editor)

	# get the comparison mode
	#
	cmpmode=$(prj_get_item $prj_cmpmode)
	applymode=$(prj_get_item $prj_applymode)
	applyfailmode=$(prj_get_item $prj_applyfailmode)
	patchseekmode=$(prj_get_item $prj_patchseekmode)
	patchvalfuzz=$(prj_get_item $prj_patchvalfuzz)
	menumode=$(prj_get_item $prj_menumode)

	# delete any "scratch" file from the indir
	#
	rm -f "$indir"/scratch

	local stat=0

	while true; do
		menu_parser
		stat=$?
		# echo "menu_parser_stat: $stat"
		[ $stat -eq $rc_run ] && break
	done
	return $stat
}

###########################################
# Parameter Initialization
###########################################
init_parms() {
	local offset=0
	local index=0
	local stat=0

	# This loop enumerates and counts the items in the project file.
	# Add new booleans to the end of the list.
	# Add new non-boolean parameters before the first boolean, but
	# after all the non-booleans.
	#
	for offset in \
	prj_menumode \
	prj_patchvalfuzz \
	prj_patchseekmode \
	prj_applyfailmode \
	prj_applymode \
	prj_cmpmode \
	prj_editor \
	prj_indir \
	prj_outdir \
	prj_colors \
	prj_background \
	prj_b_rename_infiles \
	prj_b_fmt_upstream
	do
		let index++
		let $offset=$index
		if [ "${offset:3:3}" == "_b_" ]; then
			let boolcount++
			if ! $b_found_first_bool; then
				boolindex=$index
				b_found_first_bool=true
			fi
		fi
	done

	prj_entries=$index
	[ -d "$MYDATA" ] || mkdir $MYDATA
	prj_init_prjfile $MYDATA/patchdevelop.prj $index
	stat=$?

	# If the above call to prj_init_prjfile returns nonzero, it means that a
	# new project file has been created and its values must be initialized.
	#
	if [ $stat -ne 0 ]; then
		ui_query_colors
		local newprjstr=$(
cat <<EOF
$INF
The project file has changed, or a new one has been created.

We will need to know:
1. The $STA$indirstr$INF directory to contain the patches for review
2. The $STA$outdirstr$INF directory to contain output from this script
3. Your choice of$STA diff editor
$OFF
EOF
)
		echo -e "$newprjstr"
		prj_set_directory "$indirstr" $prj_indir indir quiet
		echo
		prj_set_item $prj_outdir "$indir/tmp"
		prj_set_directory "$outdirstr" $prj_outdir outdir quiet
		echo
		set_editor
		cmpmode=$cmpmode_batch
		applymode=$applymode_norm
		applyfailmode=$applyfailmode_exit
		patchseekmode=$patchseek_off
		patchvalfuzz=0	# no tolerance for deviance!
		menumode=$menumode_ext
		prj_set_item $prj_cmpmode $cmpmode
		prj_set_item $prj_applymode $applymode
		prj_set_item $prj_applyfailmode $applyfailmode
		prj_set_item $prj_patchseekmode $patchseekmode
		prj_set_item $prj_patchvalfuzz $patchvalfuzz
		prj_set_item $prj_menumode $menumode
		prj_set_item $prj_colors $b_color		  # lib/ui.source
		prj_set_item $prj_background $terminal_background # lib/ui.source
	fi

	b_color=$(prj_get_item $prj_colors)

	if $b_color; then
		terminal_background=$(prj_get_item $prj_background)
		(( $terminal_background > 0 && $terminal_background < 3 )) || ui_get_screenbackground
		ui_set_colors
	fi

	init_booleans
	init_files
	get_booleans
	git_get_lasttag lasttag $last_tag_file
}

main_loop() {

	local stat

	# Print the Herald
	#
	echo -e "$MNU"
	echo -e " "$UND"Patch Develop $STA$version$MNU Test patches and compare to upstream$OFF"

	##############################################
	# Main Program Loop
	##############################################

	while true; do
		menu_loop
		menu_stat=$?
		# echo "menu_loop_stat: $menu_stat"

		if $b_rename_infiles; then
			exec_boolean b_rename_infiles false "renpatfiles"
			[ $? -ne 0 ] && continue
		fi

		$b_fmt_upstream && format_upstream_patches

		if [ $patchseekmode -eq $patchseek_on ]; then
			[ -f "$us_commits" ] || format_upstream_patches
			[ -f "$us_commits" ] &&	check_fixes "$us_commits"
		fi

		if [ $applymode -ne $applymode_off ]; then
			exec_apply_patches
			[ $? -ne 0 ] && continue
		fi

		[ $cmpmode -ne $cmpmode_off ] && compare_patches
	done
}

cmd_check_fixes() {
	local stat=0

	get_filecount
	$b_rename_infiles exec_boolean b_rename_infiles false "renpatfiles"

	[ -f "$us_commits" ] || format_upstream_patches
	[ -f "$us_commits" ] &&	check_fixes "$us_commits"

	return 0
}

# parse_cmdline - command line interface
#
parse_cmdline() {
	local argc=$#

	init_files

	while (( $# > 0 )) ;do
		key="$1"
		case $key in
			"-S" ) 	cmd_check_fixes
				shift
				;;
			"-R" )	renpatfiles
				shift
				;;
			   * ) 	echo "argc=$argc argv: $@"
				;;
		esac
	done

}

#############################
# main() entry point
#############################
main() {
	local argc=$#

	# Trap for control-c
	#
	trap control_c SIGINT

	! $(git_checkrepo) && git_invrepomsg && exit 1

	init_parms

	if [ $argc -eq 0 ]; then
		main_loop
	else
		parse_cmdline $@
	fi

	exit 0
}

# Call main.
# Exit when done.
#
main
exit_me 0

