#!/bin/bash
#
# prep-usb-backport
#
# NOTE:
# Requires the use of scripts gitnice and extup to create the file
# inputs for this script.


declare MYDIR=$(dirname $(which $(basename $0)))
declare MYLIB=$MYDIR/lib

source $MYLIB/ui.source

# Other exit codes
declare -i EXIT_OK=0
declare -i EXIT_INVARG=1
declare -i EXIT_INVFIL=2
declare -i EXIT_INVDIR=3
declare -i EXIT_NODIR=4
declare -i EXIT_DIRNOTEXIST=5
declare -i EXIT_UPCMT=6
declare -i EXIT_RHCMT=7
declare -i EXIT_UPDIR=8
declare -i EXIT_RHDIR=9

declare -a exitmsgary=(
""
"Invalid number of options."
" is an invalid filename."
" is an invalid directory name."
"You must provide a directory for output."
" directory does not exist."
"You must provide an upstream commit expression with the -uc option."
"You must provide a RHEL commit expression with the -rc option."
"You must provide a valid upstream repo directory with the -ur option."
"You must provied a valid RHEL repo directory with the -rr option."
)

exitme() {
	local exitval=$1
	local strarg=""
	local exitmsg

	if ([ $exitval -ne $EXIT_OK ] && [ $exitval -ne $CTLC_EXIT ]); then
		[ $# -eq 2 ] && strarg=$2
		[ ${#exitmsgary[@]} -gt $exitval ] \
			&& exitmsg="${exitmsgary[$exitval]}"

		echo -e "$BLD$strarg$exitmsg$OFF"

		[ $exitval -ne 0 ] && echo -e \
			"Type$BLD $(basename $0) -h$OFF for help."
	fi

	exit $exitval
}

# run if user hits control-c
#
control_c()
{
	echo -en "
Ctrl-c detected
Cleaning up and exiting.
"
	exitme $CTLC_EXIT
}


declare -i optcount=0
declare uplog="upstream.log"
declare rhlog="rhel.log"
declare usblog="usb-backport.log"
declare outdir=
declare upcmt=
declare rhcmt=
declare updir=
declare rhdir=

declare usagestr=$(
cat <<EOF

$(basename $0) -uc upcmt -ub updir -dc rhcmt -db rhdir outdir
  Creates a file of usb commits for backporting.

Argument:
  outdir    - The directory in which the log files are created

Options:
  -h          - this help text
  -uc upcmt   - Upstream commit expression, e.g. 'v5.6..v5.7'. Creates
                $uplog file in the outdir.
  -rc rhcmt   - RHEL commit expression, e.g. 'RHEL-8.3.0..HEAD'. Creates
                $rhlog file in the outdir.
  -ud updir   - Directory containing the uptream repo.
  -rd rhdir   - Directory containing the RHEL repo.

Example:
  $(basename $0) \\\

        -uc 'v5.7..v5.8' -ur upstream/repo/directory \\\

        -dc 'RHEL-8.3.0..HEAD' -dr RHEL/directory \\\

        backport/work/directory

\0
EOF
)

usage() {
	echo -en "$usagestr"
	exitme 0
}

# parseops() - parse the input options
#
# Needed multicharacter optionis, but didn't want to use longopts.
#
# Inputs: $@, the whole command line
#
# Globals:
# 	optcount
# 	upcmt
# 	rhcmt
# 	updir
# 	rhdir
# 	usagestr
#
parseops() {
	local arg=
	local opt=

	for arg in $@; do
	    if [ ${arg:0:1} == '-' ]; then
		opt="${arg:1}"
		case "$opt" in
		    h  ) usage
		         let ++optcount
		         ;;
		    uc ) shift
			 upcmt="$1"
			 shift
		         optcount=$((optcount + 2))
		         ;;
		    ud ) shift
			 updir="$1"
			 shift
		         optcount=$((optcount + 2))
		         ;;
		    rc ) shift
			 rhcmt="$1"
			 shift
		         optcount=$((optcount + 2))
		         ;;
		    rd ) shift
			 rhdir="$1"
			 shift
		         optcount=$((optcount + 2))
		         ;;
		    *  ) echo "unrecognized option -$1"
		         echo -e "$usagestr"
		         exit 127
		esac
	    fi
	done
}

# test_opts - test the correct number of args and options were submitted
#
# Two of the opts must point to legitimate git repos.
# The other two must be valid commit expressions.
#
test_opts() {
	[ -n "$upcmt" ] || exitme $EXIT_UPCMT
	[ -n "$rhcmt" ] || exitme $EXIT_RHCMT
	[ -d "$updir" ] || exitme $EXIT_NODIR
	[ -d "$rhdir" ] || exitme $EXIT_NODIR
	[ -d $updir/.git ] || exitme $EXIT_UPDIR
	[ -d $rhdir/.git ] || exitme $EXIT_RHDIR
}


# cmpstr() - compare strings
#    Compare the commits from the upstream and downstream commit logs
#    to identify those the ones that have already been backported.
#    Output all commit lines to the cherp.log file, marking the ones
#    that werre already backported with a leading #
#
# GLOBALS
#	usblog - output commits file
#	uplog  - upstream commits file
#	rhlog  - downstream commits file
#	outdir - directory for all the commit log files
#
cmpstr() {
	local uppath="$outdir/$uplog"
	local rhpath="$outdir/$rhlog"
	local chpath="$outdir/$usblog"
	local upstr=$(< $uppath)
	local rhstr=$(< $rhpath)
	local up	# one line from the upstream log
	local rh	# one line from the rhel log
	local tmp
	local b_match=false
#set -x
	> $chpath

	while read up; do
		upcmt="${up:0:9}"
		while read rh; do
			tmp=$(echo "$rh" | cut -d' ' -f2)
			rhcmt="${tmp:0:9}"
			[[ $rhcmt == $upcmt ]] && {
				b_match=true
				break
			}
		done <<< "$rhstr"
		$b_match && echo "# $up" >> $chpath || echo "$up" >> $chpath
		$b_match && echo "# $up" || echo "$up"
		b_match=false
	done <<< "$upstr"
#set +x
}

main() {
        # Trap for control-c
        trap control_c SIGINT

	parseops $@
	[ $optcount -lt 8 ] && exitme $EXIT_INVARG

	test_opts

	shift $optcount
	outdir="$1"

	[ -n "$outdir" ] || exitme $EXIT_NODIR
	ui_testdir "$outdir" outdir
	echo

	[ -f $outdir/$uplog ] && {
		echo -e "$BLD$outdir/$uplog$OFF exists."
		echo "You must delete it if you want to recreate it, or it will be used as is."
	} || {
		echo -e "Creating upstream commit log  : $BLD$outdir/$uplog$OFF"
	}

	[ -f $outdir/$rhlog ] && {
		echo -e "$BLD$outdir/$rhlog$OFF exists."
		echo "You must delete it if you want to recreate it, or it will be used as is."
	} || {
		echo -e "Creating RHEL commit log: $BLD$outdir/$rhlog$OFF"
	}
	echo

	printf "Upstream Repo   : $BLD%-12s$OFF RHEL Repo   : $BLD%-12s$OFF\n" $updir $rhdir
	printf "Upstream Commits: $BLD%-12s$OFF RHEL Commits: $BLD%-12s$OFF\n" $upcmt $rhcmt

	echo
	echo -n "Press any key to proceed or CTRL-C to exit..."
	read -n1

# TODO:
#
	[ -f $outdir/$uplog ] || {
		git checkout $updir
		gitnice -r -c -d $upcmt..HEAD $subsys > $outdir/$uplog
	}
	[ -f $outdir/$rhlog ] || {
		git checkout $rhdir
		extup -r $rhcmt..HEAD $subsys > $outdir/$rhlog
	}

	cmpstr

	exitme $EXIT_OK
}

main $@

exitme $EXIT_OK

