#!/bin/bash

function ui_readline {

	local lc=$(cat $2 | wc -l)
	[ $1 -gt $lc ] && return 1

	awk -v line=$1 '{
		if (NR == line) {
			print $0;
		}
	}' $2
}


function ui_replaceline {

	local lc=$(cat $3 | wc -l)
	[ $1 -gt $lc ] && return 1

	awk -v line=$1 -v new_content="$2" '{
		if (NR == line) {
			print new_content;
		} else {
			print $0;
		}
	}' $3
}

ui_replaceline $1 $2 $3

a=$(ui_readline $1 $3)
echo
echo "a = "$a""
echo

