#!/bin/bash
#
# rename-photos.sh
#
# PhotosPath="/media/4GBSD/DCIM/101CANON"
# SortPath="/home/angus/.imagesort"
# LibraryPath="/home/angus/Photos"
# CameraPath="/media/4GBSD"

function usage {
	echo
	echo "Recursively rename .jpg files from one tree and into another."
	echo ""
	echo "Usage: rename-photos source-dir dest-dir <prefix> <suffix>"
	echo "       prefix and suffix are filenaming options."
	echo
}

function min_parms {
	echo "**************************************************************"
	echo "You did not enter both the source and destination directories,"
	echo "Try again."
	echo "**************************************************************"
	echo
	exit $FAILURE
}

usage

declare -i optcount=0
declare -i argcount=1
declare prefix=""
declare suffix=""
declare PhotosPath=""
declare LibraryPath=""

declare usagestr=$(
cat <<EOF

$(basename $0) [options] <PhotosPath>

  Uses jhead to rename photos according to their exif information.

  PhotosPath  - Directory containing the photos to be renamed
  LibraryPath - Directory to receive the renamed photos

  Options
  -p prefix - to be added to the beginning of the new filename
  -s suffix - to be added at the end of the new filename
  -c dir    - copy to a different directory
\0
EOF
)

usage() {
	echo -e "$usagestr"
	exit $1
}

while getopts p:s:c: OPTION; do
    case "$OPTION" in

	p ) prefix=$OPTARG
	    optcount=$((optcount+2))
	    ;;
	s ) suffix=$OPTARG
	    optcount=$((optcount+2))
	    ;;
	c ) LibraryPath=$OPTARG
	    optcount=$((optcount+2))
	    [ -d $LibraryPath ] || {
		    echo "$LibraryPath does not exist. Exiting ..."
		    exit 1
	    }
	    ;;
        * ) echo "unrecognized option -$OPTION"
	    echo -e "$usagestr"
	    exit 127
    esac
done

shift $optcount
[ $# -eq $argcount ] || usage 1

[ "$prefix" ] && echo "Your Prefix is: $prefix" || echo "There is no prefix."
[ "$suffix" ] && echo "Your suffix is: $suffix" || echo "There is no suffix."

PhotosPath="$1"				# Source path of new photos
CharFromName=4

[ -d $PhotosPath ]  || { echo "$PhotosPath does not exist. Exiting ..."; exit1 ; }

echo "Your source directory is:       ""$PhotosPath"" having $(ls -1 $PhotosPath | wc -l) photos."
[ "$LibraryPath" ] && echo "Your destination directory is:  ""$LibraryPath"
read -p "Press any key to continue or Ctl-c to exit."

# find $PhotosPath -type f -iname '*.jpg' \
# -exec jhead -autorot -mkexif -rgt -ft -nf"$prefix"%Y-%m-%d-%H-%M-%S"$suffix" '{}' \;

find $PhotosPath -type f -iname '*.jpg' \
 -exec jhead -mkexif -ft -nf"$prefix"%Y-%m-%d-%H-%M-%S"$suffix" '{}' \;

###########
# Sort files into folders using $CharFromName letters of the file name
#
# ls $SortPath | while read file; do
#	# extract first $CharFromName characters from filename
#	FolderDate=${file:0:$CharFromName}
#	# create directory if it does not exist
#	test -d $LibraryPath/$FolderDate || mkdir $LibraryPath/$FolderDate
#	# move the current file to the destination dir
#	mv -v $SortPath/$file $LibraryPath/$FolderDate/$file
#done

[ "$LibraryPath" ] && rsync -Pvat $PhotosPath/*.jpg $LibraryPath/.

