#!/bin/bash
#
# rename-photos.sh
#
# PhotosPath="/media/4GBSD/DCIM/101CANON"
# SortPath="/home/angus/.imagesort"
# LibraryPath="/home/angus/Photos"
# CameraPath="/media/4GBSD"

function usage {
	echo
	echo "Recursively rename .jpg files from one tree and into another."
	echo ""
	echo "Usage: rename-photos source-dir dest-dir <prefix> <suffix>"
	echo "       prefix and suffix are filenaming options."
	echo
}

function min_parms {
	echo "**************************************************************"
	echo "You did not enter both the source and destination directories,"
	echo "Try again."
	echo "**************************************************************"
	echo
	exit $FAILURE
}

usage

[ $# -ge 2 ] || min_parms

PhotosPath="$1"				# Source path of new photos
# SortPath="$2"				# Default sort path
LibraryPath="$2"			# Destination path of renamed photos
CharFromName=4

declare -i optcount=0
declare -i argcount=2
declare prefix=""
declare suffix=""

declare usagestr=$(
cat <<EOF

$(basename $0) [options]
  Options
  -p prefix - 
  -s suffix - 
\0
EOF
)

usage() {
	echo -e "$usagestr"
	exit $1
}

while getopts p:s: OPTION; do
    case "$OPTION" in

	p ) prefix=$OPTARG
	    optcount=$((optcount+2))
	    ;;
	s ) suffix=$OPTARG
	    optcount=$((optcount+2))
	    ;;
	* ) echo "unrecognized option -$OPTION"
	    echo -e "$usagestr"
	    exit 127
    esac
done

shift $optcount
[ $# -ne $argcount ] || usage 1

[ "$prefix" ] && echo "Your Prefix is: $prefix" || echo "There is no prefix."
[ "$suffix" ] && echo "Your suffix is: $suffix" || echo "There is no suffix."

############
# Test to see if $PhotosPath exists, if not prompt for new path / exit.
[ -d $PhotosPath ]  || { echo "$PhotosPath does not exist. Exiting ..."; exit1 ; }
[ -d $LibraryPath ] || { echo "$LibraryPath does not exist. Exiting ..."; exit 1; }

echo "Your source directory is:       $PhotosPath having $(ls -1 $PhotosPath | wc -l) photos."
echo "Your destination directory is:  $LibraryPath"
read -p "Press any key to continue or Ctl-c to exit."

############
# rename all image files in $SortPath
# FolderDateDD-HHMMSS.ext
# jhead  -autorot -ft -nf%y%m%d-%H%M%S $SortPath/*
cd $PhotosPath

find $PhotosPath -type f -iname '*.jpg' \
 -exec jhead -autorot -mkexif -rgt -ft -nf"$prefix"%Y-%m-%d-%H-%M-%S"$suffix" '{}' \;

###########
# Sort files into folders using $CharFromName letters of the file name
#
# ls $SortPath | while read file; do
#	# extract first $CharFromName characters from filename
#	FolderDate=${file:0:$CharFromName}
#	# create directory if it does not exist
#	test -d $LibraryPath/$FolderDate || mkdir $LibraryPath/$FolderDate
#	# move the current file to the destination dir
#	mv -v $SortPath/$file $LibraryPath/$FolderDate/$file
#done

##########
# move sorted files into photo library
mv -v $PhotosPath/* $LibraryPath/

##########
# Umount the card
# umount $CameraPath

##########
# End notification
echo
echo "Photos  from: $PhotosPath"
echo "End location: $LibraryPath"
echo
