#!/bin/bash
#
# /home/tcamuso/bin/rsync-exe
#

cmdline=/home/tcamuso/bin/rsync-exe

usagestr=$(
cat <<EOF

$(basename $0) directory

Copies executables, patches, spec files and README to the destination
directory at makerpm@localhost

Simplifies copying only those files needed to create an executables-only
rpm. This sidesteps the need to build the executables from scratch on
the target system.

\0
EOF
)

usage() {
	echo -e "$usagestr"
	exit
}

[ $# -gt 0 ] || usage

declare directory="$1"
declare exelist=$(find ./ -maxdepth 1 -type f -executable)
alias rsyncp='rsync -Pvat -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"'

rsyncp ./{$exelist,*.spec,*.patch,README} makerpm@localhost:"$directory"
