#!/bin/bash
# runremote (revised, not dependent upon /dev/stdin)
# usage: runremote.sh <remoteuser> <remotehost> <localscript> arg1 arg2 ...

user=$1
host=$2
realscript=$3
shift 3

# escape the arguments
declare -a args

sshcmd="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

count=0
for arg in "$@"; do
  args[count]=$(printf '%q' "$arg")
  count=$((count+1))
done

{
  printf '%s\n' "set -- ${args[*]}"
  cat "$realscript"
} | $sshcmd $user@$host "bash -s"
