#!/bin/bash
#This script will automatically suspend and resume the system.

########################################################################################
# The looping script

# Log file
LOG_FILE=/var/tmp/S3_Suspend_message.log
sleep_time=60
wake_after=30

echo "The log file $LOG_FILE will be created."
echo "" > $LOG_FILE

read -p "Number of iterations: " count
echo "************************************************************************" | tee -a $LOG_FILE
echo " START" | tee -a $LOG_FILE
echo "************************************************************************" | tee -a $LOG_FILE
echo "" | tee -a $LOG_FILE

for((loop=1;loop<=$count;loop++))
do
#record the suspend and resume log
	date | tee -a $LOG_FILE
	dmesg | tee -a $LOG_FILE
	echo "The system will suspend after $sleep_time seconds and resume after $wake_after seconds when it's in S3."
	sleep $sleep_time
	rtcwake --mode=mem --second=$wake_after
	echo "#######################################################################" | tee -a $LOG_FILE
	echo "Wake up: $loop of: $count" | tee -a $LOG_FILE
	echo "#######################################################################" | tee -a $LOG_FILE
done
#Change mod of log file
chmod 777 $LOG_FILE
echo "Please check $LOG_FILE."
exit 0

