#!/bin/bash
#
# timer
#

cmdline=timer

usagestr=$(
cat <<EOF

timer
\0
EOF
)

usage() {
	echo -e "$usagestr"
	exit
}

[ $# -gt 0 ] || usage

cmd="$@"

START1=$(date +%s)

echo $cmd
read -n1

eval $cmd

END=$(date +%s)
DIFF=$(( $END - $START1 ))

minutes=$(( $DIFF / 60 ))
seconds=$(( $DIFF % 60 ))
echo
echo "That took $minutes minutes and $seconds seconds."
echo

