#!/bin/bash
#
# timer
#

cmdline=timer

usagestr=$(
cat <<EOF

timer - simple timing wrapper for the command line

Returns the elapsed time that it took for the command to execute.
\0
EOF
)

usage() {
	echo -e "$usagestr"
	exit
}

[ $# -gt 0 ] || usage

cmd="$@"
declare scriptfile="__timer__"

echo 'START1=$(date +%s)' 		> $scriptfile
echo "$cmd" 				>> $scriptfile
echo 'END=$(date +%s)' 			>> $scriptfile
echo 'DIFF=$(($END - $START1))' 	>> $scriptfile
echo 'minutes=$(($DIFF / 60))'		>> $scriptfile
echo 'seconds=$(($DIFF % 60))'		>> $scriptfile
echo					>> $scriptfile
echo 'echo "That took $minutes minutes and $seconds seconds."'	>> $scriptfile
echo 'echo'				>> $scriptfile

chmod +x $scriptfile
./$scriptfile
rm -f $scriptfile
