#!/bin/bash
#
# wcherp
#

[ -n "$MYDIR" ] || {
	declare MYDIR=
	MYDIR="$(dirname -- "${0}")"
}

[ -n "$MYLIB" ] || {
	declare MYLIB=
	MYLIB="$MYDIR"/lib
}

[ "$ui_loaded" ]        || source "$MYLIB"/ui.source
[ "$ptversion_loaded" ] || source "$MYLIB"/patchtools-version.source

declare usagestr=
usagestr="$(
cat <<EOF

$(basename "$0") [options]

Options
-------
-V : split screen vertically (default)
-H : split screen horizontally

This script spawns the cherp backport script as a split screen.
One pane has cherp running in it, the other has vim with the
backport commits file containing commits to be backported
from upstream,

The required screen splitter is tmux. If it is not installed,
you will be prompted whether you want to install it. The
script will exit if tmux is not installed and you don't want
to install it.
\0
EOF
)"

declare intro
intro="$(
cat <<EOF

\0
EOF
)"

declare b_vertical=true

usage() {
	echo -e "$usagestr"
	exit 0
}

exitme() {
	exit $1
}

# control_c: run if user hits control-c
#
# Global
#   CTLC_EXIT - bash environment variable
#
control_c() {
	echo -e "\nCtrl-c detected\nCleaning up and exiting."
	exit $CTLC_EXIT
}

parseops() {
	local arg=
	local opt=

	while (($# > 0)); do
	    arg="$1"

	    if [ "${arg:0:1}" == '-' ]; then
		opt="${arg:1}"

		case "$opt" in
		    H ) b_vertical=false
			;;
		    V ) b_vertical=true
			;;
		    *  ) echo "unrecognized option $arg"
			 echo -e "$usagestr"
			 exitme 127
		esac
	    fi

	    shift
	done
}

main() {
	local myb
	local errstr

	[[ $1 =~ (-h|^help) ]] && usage
	ui_setbg mybg

	errstr=$(rpm -q tmux) || {
		echo -e	"\n$WRN$errstr$OFF\n"
		loop_yn "${MNU}Would you like to install tmux now? y/n : $OFF" || exitme 1
		sudo dnf install -y tmux
	}

	parseops "$@"

	if $b_vertical && ((tcols < 200)); then
		echo -e "$WRN Your terminal window only has $STA$tcols$WRN columns.$OFF\n" \
		        "Please change your terminal width to at least 200 columns\n"
		exitme 1
	fi

	if ! $b_vertical && ((tlines < 60)); then
		echo -e "$WRN Your terminal window only has $STA$tlines$WRN lines.$OFF\n" \
			"Please change your terminal length to at least 60 lines\n"
		exitme 1
	fi

	echo -e "$MNU$UND"
	echo -e "Patchtools $version$OFF"

	# Start tmux session with vertically split window
	tmux new-session -d -s mysession

	# Split the window vertically
	tmux split-window -h

	# Run your script in the left pane
	tmux send-keys -t mysession:0.0 'your_script.sh' Enter

	# Display a text file in the right pane (replace 'your_text_file.txt' with your file)
	tmux send-keys -t mysession:0.1 'cat your_text_file.txt' Enter

	# Attach to the session
	tmux attach-session -t mysession

	ui_exit ui_exit_ok
}

main "$@"
