#!/bin/bash

function usage {
	echo
	echo "cpuinfo string"
	echo
	echo -e "\tThe \"string\" argument can be any string or substring"
	echo -e "\tin the first field of /proc/cpuinfo"
	echo
	exit
}

[ "$1" == "-h" ] && usage
[ -z "$1" ] && usage

cpu_count=$(cat /proc/cpuinfo | grep processor | wc -l)
line_count=$(cat /proc/cpuinfo | wc -l)
for (( i = 0; i < (line_count/cpu_count); i++ ))
do
	read line
	parm=${line%%:*}
	[[ "$parm" =~ "$1" ]] && echo $line
done < /proc/cpuinfo

# cat /proc/cpuinfo | grep "$1" | head -n1
