#!/bin/bash

echo "current directory $PWD"
cd $HOME
echo "changed to home directory $PWD"
tar -xvf bin.tgz
tar -xvf code.tgz
tar -xvf hints.tgz

if ! [ -d Kernel-Course ]; then
	mkdir Kernel-Course/
fi

unzip -o Kernel-Course.zip -d Kernel-Course/
mv .bashrc .bashrc.orig
cp -f bin/.bashrc ~/.
cp -f bin/.vimrc ~/.
cd -
echo "back to current directory $PWD"

exit 0
